const sswPMData = {
  2: [
    { kanji: "飲料", kana: "いんりょう", correct: "minuman" },
    { kanji: "食料品", kana: "しょくりょうひん", correct: "bahan makanan" },
    { kanji: "欠かせません", kana: "かかせません", correct: "ini penting" },
    { kanji: "製造する", kana: "せいぞうする", correct: "pembuatan" },
    { kanji: "飲食料品製造業", kana: "いんしょくりょうひんせいぞうぎょう", correct: "industri manufaktur makanan dan minuman" },
    { kanji: "ハムソーセージ", kana: "ハムソーセージ", correct: "sosis daging" },
    { kanji: "魚の缶詰", kana: "さかなのかんづめ", correct: "ikan kaleng" },
    { kanji: "惣菜", kana: "そうざい", correct: "makanan pendamping" },
    { kanji: "冷凍食品", kana: "れいとうしょくひん", correct: "makanan beku" },
    { kanji: "農林水産省", kana: "のうりんすいさんしょう", correct: "Kementerian Pertanian, Kehutanan dan Perikanan" },
    { kanji: "統計", kana: "とうけい", correct: "statistik" },
    { kanji: "国内生産額", kana: "こくないせいさんがく", correct: "jumlah produksi dalam negeri" },
    { kanji: "数年", kana: "すうねん", correct: "beberapa tahun" },
    { kanji: "兆円", kana: "ちょうえん", correct: "triliun yen" }
  ],
  3: [
    { kanji: "特定技能1号", kana: "とくていぎのう1ごう", correct: "keahlian khusus tingkat 1" },
    { kanji: "在留資格者", kana: "ざいりゅうしかくしゃ", correct: "orang berstatus penduduk" },
    { kanji: "業種", kana: "ぎょうしゅ", correct: "industri" },
    { kanji: "食品衛生", kana: "しょくひんえいせい", correct: "kebersihan makanan" },
    { kanji: "労働安全", kana: "ろうどうあんぜん", correct: "keselamatan kerja" },
    { kanji: "知識", kana: "ちしき", correct: "pengetahuan" },
    { kanji: "技能", kana: "ぎのう", correct: "keahlian" },
    { kanji: "必要", kana: "ひつよう", correct: "membutuhkan" },
    { kanji: "命", kana: "いのち", correct: "kehidupan" },
    { kanji: "生命", kana: "せいめい", correct: "kehidupan" },
    { kanji: "守る", kana: "まもる", correct: "melindungi" },
    { kanji: "信用", kana: "しんよう", correct: "kredibilitas" },
    { kanji: "安全保護具", kana: "あんぜんほごぐ", correct: "peralatan perlindungan keselamatan" },
    { kanji: "着用", kana: "ちゃくよう", correct: "memakai" },
    { kanji: "作業者", kana: "さぎょうしゃ", correct: "pekerja" },
    { kanji: "健康", kana: "けんこう", correct: "kesehatan" }
  ],
  5: [
    { kanji: "基本", kana: "きほん", correct: "dasar" },
    { kanji: "行動", kana: "こうどう", correct: "tindakan" },
    { kanji: "清潔", kana: "せいけつ", correct: "kebersihan" },
    { kanji: "設備", kana: "せつび", correct: "fasilitas" },
    { kanji: "保管", kana: "ほかん", correct: "penyimpanan" },
    { kanji: "共通する", kana: "きょうつうする", correct: "memiliki kesamaan" },
    { kanji: "一般", kana: "いっぱん", correct: "umum" },
    { kanji: "重要", kana: "じゅうよう", correct: "penting" },
    { kanji: "施設", kana: "しせつ", correct: "fasilitas" },
    { kanji: "種類", kana: "しゅるい", correct: "jenis" },
    { kanji: "特徴", kana: "とくちょう", correct: "fitur" },
    { kanji: "応じて", kana: "おうじて", correct: "bergantung kepada" },
    { kanji: "工程", kana: "こうてい", correct: "proses" },
    { kanji: "組み合わせて", kana: "くみあわせて", correct: "dalam kombinasi" }
  ],
  6: [
    { kanji: "危害要因", kana: "きがいよういん", correct: "faktor bahaya" },
    { kanji: "含まれない", kana: "ふくまれない", correct: "tidak termasuk" },
    { kanji: "活动", kana: "かつどう", correct: "aktivitas" },
    { kanji: "学習する", kana: "がくしゅうする", correct: "mempelajari" }
  ],
  7: [
    { kanji: "物理的危害要因", kana: "ぶつりてききがいよういん", correct: "bahaya fisik" },
    { kanji: "化学的危害要因", kana: "かがくてききがいよういん", correct: "bahaya kimia" },
    { kanji: "生物的危害要因", kana: "せいぶつてききがいよういん", correct: "bahaya biologis" },
    { kanji: "硬い", kana: "かたい", correct: "keras" },
    { kanji: "歯が欠ける", kana: "はがかける", correct: "gigi terkelupas" },
    { kanji: "尖って", kana: "とがって", correct: "Lancip" },
    { kanji: "傷", kana: "きず", correct: "menggores/tergores" },
    { kanji: "代表的な", kana: "だいひょうてき", correct: "perwakilan" },
    { kanji: "金属片", kana: "きんぞくへん", correct: "serpihan logam" },
    { kanji: "ガラス片", kana: "ガラスへん", correct: "sepotong kaca" },
    { kanji: "プラスチック片", kana: "プラスチックへん", correct: "potongan plastik" },
    { kanji: "石", kana: "いし", correct: "batu" },
    { kanji: "原材料", kana: "げんざいりょう", correct: "bahan baku" },
    { kanji: "取り除く", kana: "とりのぞく", correct: "menghapus" },
    { kanji: "異物", kana: "いぶつ", correct: "benda asing" },
    { kanji: "卵の殻", kana: "たまごのから", correct: "kulit telur" },
    { kanji: "硬質異物", kana: "こうしついぶつ", correct: "benda asing yang keras" },
    { kanji: "混入", kana: "こんにゅう", correct: "kontaminasi" },
    { kanji: "防止", kana: "ぼうし", correct: "pencegahan" },
    { kanji: "土", kana: "つち", correct: "tanah" },
    { kanji: "小石", kana: "こいし", correct: "kerikil" },
    { kanji: "洗浄", kana: "せんじょう", correct: "Pencucian" },
    { kanji: "選別", kana: "せんべつ", correct: "penyortiran" },
    { kanji: "下処理", kana: "したしょり", correct: "persiapan" },
    { kanji: "野菜の根の部分", kana: "やさいのねのぶぶん", correct: "bagian akar sayuran" },
    { kanji: "貝の殻", kana: "かいのから", correct: "kerang laut" },
    { kanji: "魚のエラ", kana: "さかなのえら", correct: "insang ikan" },
    { kanji: "骨", kana: "ほね", correct: "tulang" }
  ],
  8: [
    { kanji: "蓋", kana: "ふた", correct: "tutup" },
    { kanji: "紙片", kana: "しへん", correct: "selembar kertas" },
    { kanji: "不潔", kana: "ふけつ", correct: "kekotoran" },
    { kanji: "不衛生", kana: "ふえいせい", correct: "tidak sehat" },
    { kanji: "苦情(クレーム)", kana: "くじょう", correct: "keluhan (klaim)" },
    { kanji: "返品", kana: "へんぴん", correct: "kembali" },
    { kanji: "会社の信用", kana: "かいしゃのしんよう", correct: "kepercayaan perusahaan" },
    { kanji: "落とす", kana: "おとす", correct: "menjatuhkan" },
    { kanji: "物質", kana: "ぶっしつ", correct: "bahan" },
    { kanji: "ヒスタミン", kana: "ヒスタミン", correct: "histamin" },
    { kanji: "じゃがいもの芽", kana: "じゃがいものめ", correct: "kecambah kentang" },
    { kanji: "ソラニン", kana: "ソラニン", correct: "solanin" },
    { kanji: "殺菌剤", kana: "さっきんざい", correct: "fungisida" },
    { kanji: "薬剤", kana: "やくざい", correct: "obat" },
    { kanji: "化学物質", kana: "かがくぶっしつ", correct: "bahan kimia" },
    { kanji: "反応", kana: "はんのう", correct: "reaksi" },
    { kanji: "過剰", kana: "かじょう", correct: "kelebihan" },
    { kanji: "症状", kana: "しょうじょう", correct: "gejala" },
    { kanji: "かゆみ", kana: "かゆみ", correct: "gatal" },
    { kanji: "じんましん", kana: "じんましん", correct: "sarang lebah" },
    { kanji: "唇", kana: "くちびる", correct: "bibir" },
    { kanji: "まぶたの腫れ", kana: "まぶたのはれ", correct: "pembengkakan kelopak mata" },
    { kanji: "法律", kana: "ほうりつ", correct: "hukum" },
    { kanji: "発症数", kana: "はっしょうすう", correct: "jumlah kasus" },
    { kanji: "加工食品", kana: "かこうしょくひん", correct: "makanan olahan" },
    { kanji: "表示", kana: "ひょうじ", correct: "menampilkan" },
    { kanji: "義務", kana: "ぎむ", correct: "tugas" },
    { kanji: "推奨", kana: "すいしょう", correct: "rekomendasi" },
    { kanji: "準ずるもの", kana: "じゅんずるもの", correct: "setara" }
  ],
  9: [
    { kanji: "品目", kana: "ひんもく", correct: "barang" },
    { kanji: "くるみ", kana: "くるみ", correct: "kenari" },
    { kanji: "移される", kana: "うつされる", correct: "dipindahkan" },
    { kanji: "調理", kana: "ちょうり", correct: "memasak" },
    { kanji: "まな板", kana: "まないた", correct: "talenan" },
    { kanji: "包丁", kana: "ほうちょう", correct: "pisau" },
    { kanji: "ゆで卵", kana: "ゆでたまご", correct: "telur rebus" },
    { kanji: "洗浄剤", kana: "せんじょうざい", correct: "sabun cuci" },
    { kanji: "残らない", kana: "のこらない", correct: "tidak ketinggalan" },
    { kanji: "流す", kana: "ながす", correct: "mengalir" },
    { kanji: "獲った", kana: "とった", correct: "tertangkap" },
    { kanji: "条件", kana: "じょうけん", correct: "kondisi" },
    { kanji: "マグロ", kana: "マグロ", correct: "tuna" },
    { kanji: "イワシ", kana: "イワシ", correct: "sarden" },
    { kanji: "サバ", kana: "サバ", correct: "ikan kembung" }
  ],
  10: [
    { kanji: "赤身魚", kana: "あかみざかな", correct: "ikan merah" },
    { kanji: "似た", kana: "にた", correct: "sama" },
    { kanji: "増える", kana: "ふえる", correct: "meningkatkan" },
    { kanji: "じゃがいもの芽", kana: "じゃがいものめ", correct: "kecambah/tunas kentang" },
    { kanji: "吐き気", kana: "はきけ", correct: "mual" },
    { kanji: "おう吐", kana: "おうと", correct: "muntah" },
    { kanji: "下痢", kana: "げり", correct: "diare" },
    { kanji: "腹痛", kana: "ふくつう", correct: "sakit perut" },
    { kanji: "頭痛", kana: "ずつう", correct: "sakit kepala" },
    { kanji: "食中毒", kana: "しょくちゅうどく", correct: "keracunan makanan" },
    { kanji: "取り除く", kana: "とりのぞく", correct: "menghapus" },
    { kanji: "防ぐ", kana: "ふせぐ", correct: "mencegah" },
    { kanji: "細菌", kana: "さいきん", correct: "bakteri" },
    { kanji: "寄生虫", kana: "きせいちゅう", correct: "parasit" },
    { kanji: "カビ", kana: "カビ", correct: "jamur" },
    { kanji: "病原", kana: "びょうげん", correct: "Patogen" },
    { kanji: "顕微鏡", kana: "けんびきょう", correct: "mikroskop" },
    { kanji: "生き物", kana: "いきもの", correct: "makhluk hidup" }
  ],
  11: [
    { kanji: "発症する", kana: "はっしょうする", correct: "mengembangkan gejala" },
    { kanji: "鶏卵", kana: "けいらん", correct: "telur ayam" },
    { kanji: "魚介類", kana: "ぎょかいるい", correct: "makanan laut" },
    { kanji: "激しい下痢", kana: "はげしいげり", correct: "diare parah" },
    { kanji: "毒素", kana: "どくそ", correct: "toksin/racun" },
    { kanji: "井戸水", kana: "いどみず", correct: "air sumur" },
    { kanji: "血便", kana: "けつべん", correct: "tinja berdarah" },
    { kanji: "皮膚", kana: "ひふ", correct: "kulit" },
    { kanji: "傷", kana: "きず", correct: "menggores" },
    { kanji: "芽胞", kana: "がほう", correct: "spora" },
    { kanji: "呼吸困難", kana: "こきゅうこんなん", correct: "sulit bernafas" }
  ],
  12: [
    { kanji: "発生", kana: "はっせい", correct: "kejadian" },
    { kanji: "食中毒", kana: "しょくちゅうどく", correct: "keracunan makanan" },
    { kanji: "予防", kana: "よぼう", correct: "pencegahan" },
    { kanji: "つけない", kana: "つけない", correct: "jangan memakainya" },
    { kanji: "増やさない", kana: "ふやさない", correct: "jangan menambah" },
    { kanji: "やっつける(ころす)", kana: "やっつける(ころす)", correct: "kekalahan (membunuh)" },
    { kanji: "作業開始前", kana: "さぎょうかいしまえ", correct: "sebelum mulai bekerja" },
    { kanji: "温度", kana: "おんど", correct: "suhu" },
    { kanji: "水分", kana: "すいぶん", correct: "kelembaban" },
    { kanji: "栄養", kana: "えいよう", correct: "nutrisi" },
    { kanji: "湿度", kana: "しつど", correct: "kelembaban" },
    { kanji: "環境", kana: "かんきょう", correct: "lingkungan" },
    { kanji: "好み", kana: "このみ", correct: "menyukai" },
    { kanji: "加熱", kana: "かねつ", correct: "pemanasan" }
  ],
  13: [
    { kanji: "厳しい", kana: "きびしい", correct: "ketat" },
    { kanji: "濃度の薬剤", kana: "のうどのやくざい", correct: "obat konsentrasi" },
    { kanji: "食品全体", kana: "しょくひんぜんたい", correct: "semua makanan" },
    { kanji: "冷やす", kana: "ひやす", correct: "dingin" },
    { kanji: "代表的", kana: "だいひょうてき", correct: "perwakilan" },
    { kanji: "牡蠣", kana: "かき", correct: "tiram" },
    { kanji: "汚染", kana: "おせん", correct: "polusi" },
    { kanji: "大便", kana: "だいべん", correct: "kotoran" },
    { kanji: "吐いた", kana: "はいた", correct: "muntah" },
    { kanji: "次亜塩素酸ナトリウム", kana: "じあえんそさん", correct: "Natrium hipoklorit" },
    { kanji: "溶液", kana: "ようえき", correct: "larutan" },
    { kanji: "布巾", kana: "ふきん", correct: "kain untuk pencuci piring" },
    { kanji: "原則", kana: "げんそく", correct: "prinsip" },
    { kanji: "対策", kana: "たいさく", correct: "tindakan" },
    { kanji: "有効", kana: "ゆうこう", correct: "efektif" }
  ],
  14: [
    { kanji: "食品製造工場", kana: "しょくひんせいぞうこうじょう", correct: "pabrik pembuatan makanan" },
    { kanji: "持ち込まない", kana: "もちこまない", correct: "jangan membawanya masuk" },
    { kanji: "感染", kana: "かんせん", correct: "infeksi" },
    { kanji: "消毒", kana: "しょうどく", correct: "desinfeksi" },
    { kanji: "おう吐物", kana: "おうとぶつ", correct: "muntah" },
    { kanji: "専門用具", kana: "せんもんようぐ", correct: "alat khusus" },
    { kanji: "処理する", kana: "しょりする", correct: "proses" },
    { kanji: "広げない", kana: "ひろげない", correct: "jangan menyebar" },
    { kanji: "カビ", kana: "カビ", correct: "jamur" },
    { kanji: "増殖", kana: "ぞうしょく", correct: "berkembang biak" },
    { kanji: "胞子", kana: "ほうし", correct: "spora" },
    { kanji: "存在", kana: "そんざい", correct: "adanya" },
    { kanji: "完全", kana: "かんぜん", correct: "Sempurna" },
    { kanji: "豆", kana: "まめ", correct: "kacang polong" },
    { kanji: "穀類", kana: "こくるい", correct: "biji-bijian" },
    { kanji: "生えた", kana: "はえた", correct: "dewasa" },
    { kanji: "寄生虫", kana: "きせいちゅう", correct: "parasit" },
    { kanji: "表面", kana: "ひょうめん", correct: "permukaan" },
    { kanji: "体内", kana: "たいない", correct: "didalam tubuh" },
    { kanji: "アニサキス", kana: "アニサキス", correct: "anisakis" },
    { kanji: "魚介類", kana: "ぎょかいるい", correct: "makanan laut" },
    { kanji: "生", kana: "なま", correct: "mentah" }
  ],
  15: [
    { kanji: "共通", kana: "きょうつう", correct: "umum" },
    { kanji: "整理", kana: "せいり", correct: "meringkas" },
    { kanji: "整頓", kana: "せいとん", correct: "merapikan" },
    { kanji: "清掃", kana: "せいそう", correct: "pembersihan" },
    { kanji: "清潔", kana: "せいけつ", correct: "merawat" },
    { kanji: "習慣付", kana: "しゅうかんづけ", correct: "membiasakan" },
    { kanji: "しつけ", kana: "しつけ", correct: "disiplin" },
    { kanji: "取出せる", kana: "とりだせる", correct: "bisa dikeluarkan" },
    { kanji: "順序", kana: "じゅんじょ", correct: "urutan" },
    { kanji: "数量", kana: "すうりょう", correct: "kuantitas,jumlah" },
    { kanji: "表示", kana: "ひょうじ", correct: "menampilkan" },
    { kanji: "磨く", kana: "みがく", correct: "menggosok" },
    { kanji: "拭いたり", kana: "ふいたり", correct: "mengelap" },
    { kanji: "見た目", kana: "みため", correct: "terlihat" },
    { kanji: "とおりに", kana: "とおりに", correct: "sesuai,berdasarkan" },
    { kanji: "実行", kana: "じっこう", correct: "eksekusi" },
    { kanji: "保つ", kana: "たもつ", correct: "menjaga" },
    { kanji: "手指", kana: "てゆび", correct: "jari" }
  ],
  16: [
    { kanji: "役立ちます", kana: "やくだちます", correct: "bermanfaat" },
    { kanji: "触れる", kana: "ふれる", correct: "menyentuh" },
    { kanji: "交差汚染", kana: "こうさおせん", correct: "kontaminasi silang" },
    { kanji: "使い分け", kana: "つかい分け", correct: "Penggunaan yang tepat" },
    { kanji: "通常", kana: "つうじょう", correct: "biasanya" },
    { kanji: "清潔作業区域", kana: "せいけつさぎょうくいき", correct: "area kerja yang bersih" },
    { kanji: "準清潔作業区域", kana: "じゅんせいけつさぎょうくいき", correct: "Area kerja semi-bersih" },
    { kanji: "汚染作業区域", kana: "おせんさぎょうくいき", correct: "area kerja yang terkontaminasi" },
    { kanji: "ゾーニング", kana: "ゾーニング", correct: "zonasi" },
    { kanji: "区分衛生管理", kana: "くぶんえいせいかんり", correct: "manajemen kebersihan terpisah" },
    { kanji: "取り扱い", kana: "とりあつかい", correct: "penanganan" },
    { kanji: "下処理", kana: "したしょり", correct: "Persiapan" },
    { kanji: "出荷", kana: "しゅっか", correct: "pengiriman" },
    { kanji: "詰めた", kana: "つめた", correct: "diisi" }
  ],
  17: [
    { kanji: "通らない", kana: "とおらない", correct: "tidak melewati" },
    { kanji: "ほこり", kana: "ほこり", correct: "debu" },
    { kanji: "不要", kana: "ふよう", correct: "Tidak perlu" },
    { kanji: "通路", kana: "つうろ", correct: "lorong" },
    { kanji: "定期的", kana: "ていきてき", correct: "Secara teratur" },
    { kanji: "ネズミ", kana: "ネズミ", correct: "tikus" },
    { kanji: "虫", kana: "むし", correct: "serangga" },
    { kanji: "状況", kana: "じょうきょう", correct: "situasi" },
    { kanji: "排水溝", kana: "はいすいこう", correct: "mengeringkan" },
    { kanji: "ミキサー", kana: "ミキサー", correct: "mixer" },
    { kanji: "スライサー", kana: "スライサー", correct: "alat pengiris" },
    { kanji: "分解", kana: "ぶんかい", correct: "membongkar" },
    { kanji: "目立つ", kana: "めだつ", correct: "menonjol,mencolok" },
    { kanji: "直接", kana: "ちょくせつ", correct: "secara langsung" }
  ],
  18: [
    { kanji: "乾燥する", kana: "かんそうする", correct: "pengeringan" },
    { kanji: "たわし", kana: "たわし", correct: "penggosok" },
    { kanji: "濡れる", kana: "ぬれる", correct: "menjadi basah" },
    { kanji: "発生", kana: "はっせい", correct: "kejadian" },
    { kanji: "皮膚", kana: "ひふ", correct: "kulit" },
    { kanji: "保管庫", kana: "ほかんこ", correct: "gudang" },
    { kanji: "名称", kana: "めいしょう", correct: "nama" }
  ],
  19: [
    { kanji: "健康", kana: "けんこう", correct: "kesehatan" },
    { kanji: "職場", kana: "しょくば", correct: "tempat kerja" },
    { kanji: "定期的", kana: "ていきてき", correct: "secara teratur" },
    { kanji: "健康診断", kana: "けんこうしんだん", correct: "cek kesehatan" },
    { kanji: "検便", kana: "けんべん", correct: "tes tinja" },
    { kanji: "汚れ", kana: "よごれ", correct: "kotor" },
    { kanji: "異物", kana: "いぶつ", correct: "Benda asing" },
    { kanji: "更衣室", kana: "こういしつ", correct: "ruang ganti" },
    { kanji: "つけ爪", kana: "つけつめ", correct: "kuku palsu" },
    { kanji: "イヤリング", kana: "イヤリング", correct: "anting-anting" },
    { kanji: "ネックレス", kana: "ネックレス", correct: "kalung" },
    { kanji: "ピアス", kana: "ピアス", correct: "anting-anting" },
    { kanji: "鏡", kana: "かがみ", correct: "cermin" },
    { kanji: "衣服", kana: "いふく", correct: "pakaian" }
  ],
  20: [
    { kanji: "順序", kana: "じゅんじょ", correct: "urutan" },
    { kanji: "頭髪", kana: "とうはつ", correct: "rambut" },
    { kanji: "ブラッシング", kana: "ブラッシング", correct: "menyisir" },
    { kanji: "かぶります", kana: "かぶります", correct: "memakai (kepala)" },
    { kanji: "留めます", kana: "とめます", correct: "kancingkan" },
    { kanji: "服装", kana: "ふくそう", correct: "pakaian" }
  ],
  21: [
    { kanji: "粘着ローラ", kana: "ねんちゃく", correct: "rol perekat" },
    { kanji: "エアーシャワー", kana: "エアーシャワー", correct: "pancuran udara" },
    { kanji: "履き物", kana: "はきもの", correct: "alas kaki" },
    { kanji: "履き替える", kana: "はきかえる", correct: "ganti sepatu" }
  ],
  22: [
    { kanji: "絞り", kana: "しぼり", correct: "bukaan" },
    { kanji: "端", kana: "はし", correct: "akhir" },
    { kanji: "襟", kana: "えり", correct: "kerah" },
    { kanji: "付着", kana: "ふちゃく", correct: "adhesi" },
    { kanji: "縦襟", kana: "たてえり", correct: "kerah vertikal" },
    { kanji: "エプロン", kana: "エプロン", correct: "celemek" },
    { kanji: "腕カバー", kana: "うでカバー", correct: "penutup lengan" },
    { kanji: "ふかく", kana: "ふかく", correct: "dalam kombinasi" },
    { kanji: "合ってる", kana: "あってる", correct: "cocok" },
    { kanji: "袖", kana: "そで", correct: "lengan baju" }
  ],
  24: [
    { kanji: "直前", kana: "直前", correct: "Sebelum" },
    { kanji: "盛り付け", kana: "もりつけ", correct: "pengaturan" },
    { kanji: "汚染作業区域", kana: "おせんさぎょうくいき", correct: "area kerja yang terkontaminasi" },
    { kanji: "非汚染作業区域", kana: "ひおせんさぎょうくいき", correct: "area kerja yang tidak terkontaminasi" }
  ],
  25: [
    { kanji: "流水", kana: "りゅうすい", correct: "air mengalir" },
    { kanji: "せっけん", kana: "せっけん", correct: "sabun mandi" },
    { kanji: "指の先", kana: "ゆびのさき", correct: "ujung jari" },
    { kanji: "秒間程度", kana: "びょうかんていど", correct: "sekitar detik" },
    { kanji: "流す", kana: "ながす", correct: "mengalir" },
    { kanji: "乾かす", kana: "かわかす", correct: "kering" },
    { kanji: "両手", kana: "りょうて", correct: "kedua tangan" },
    { kanji: "吹付", kana: "ふきつけ", correct: "penyemprotan" },
    { kanji: "すりこむ", kana: "すりこむ", correct: "gosokkan" }
  ],
  26: [
    { kanji: "交換", kana: "こうかん", correct: "menukarkan,mengganti" },
    { kanji: "徹底", kana: "てってい", correct: "ketelitian" },
    { kanji: "殺菌済み", kana: "さっきんずみ", correct: "disterilkan" },
    { kanji: "不備", kana: "ふび", correct: "kekurangan" },
    { kanji: "たんや", kana: "たんや", correct: "Tanya" },
    { kanji: "つば", kana: "つば", correct: "meludah" },
    { kanji: "吐いて", kana: "はいて", correct: "Muntah" },
    { kanji: "せき", kana: "せき", correct: "batuk" },
    { kanji: "関係", kana: "かんけい", correct: "hubungan" }
  ],
  27: [
    { kanji: "ホチキスの針", kana: "はり", correct: "stapler" },
    { kanji: "臭い", kana: "におい", correct: "bau" },
    { kanji: "品質", kana: "ひんしつ", correct: "kualitas" },
    { kanji: "影響", kana: "えいきょう", correct: "pengaruh" },
    { kanji: "香水", kana: "こうすい", correct: "parfum" },
    { kanji: "意図的", kana: "いとてき", correct: "disengaja" },
    { kanji: "記録", kana: "きろく", correct: "catatan" },
    { kanji: "倉庫", kana: "そうこ", correct: "gudang" },
    { kanji: "外部", kana: "がいぶ", correct: "luar" },
    { kanji: "照らし合わせて", kana: "てらしあわせて", correct: "dibandingkan" },
    { kanji: "届く", kana: "とどく", correct: "sampai" },
    { kanji: "受入検査", kana: "うけいれけんさ", correct: "Inspeksi,pengecekan penerimaan" },
    { kanji: "期限", kana: "きげん", correct: "tenggang waktu" },
    { kanji: "保存", kana: "ほぞん", correct: "menyimpan" },
    { kanji: "表示", kana: "ひょうじ", correct: "menampilkan" },
    { kanji: "品温", kana: "ひんおん", correct: "Suhu produk" },
    { kanji: "腐敗", kana: "ふはい", correct: "busuk" },
    { kanji: "包装", kana: "ほうそう", correct: "kemasan" }
  ],
  28: [
    { kanji: "消費期限", kana: "しょうひきげん", correct: "tanggal habis tempo" },
    { kanji: "適切", kana: "てきせつ", correct: "sesuai" },
    { kanji: "返品", kana: "へんぴん", correct: "kembali" },
    { kanji: "交換", kana: "こうかん", correct: "menukarkan" },
    { kanji: "合格", kana: "ごうかく", correct: "lulus" }
  ],
  29: [
    { kanji: "種類", kana: "しゅるい", correct: "jenis" },
    { kanji: "異なる", kana: "ことなる", correct: "berbeda" },
    { kanji: "冷凍水産物", kana: "れいとうすいさんぶつ", correct: "makanan laut beku" }
  ],
  30: [
    { kanji: "隙間", kana: "すきま", correct: "celah" },
    { kanji: "詰め込んで", kana: "つめこんで", correct: "Penuh sesak" },
    { kanji: "全体", kana: "ぜんたい", correct: "seluruh" },
    { kanji: "回らない", kana: "まわらない", correct: "tidak berputar" },
    { kanji: "割詰めた", kana: "わりつめた", correct: "potong itu" },
    { kanji: "互いに", kana: "たがいに", correct: "satu sama lain" },
    { kanji: "冷やす", kana: "ひやす", correct: "dingin" },
    { kanji: "節電", kana: "せつでん", correct: "penghematan energi" },
    { kanji: "低温", kana: "ていおん", correct: "suhu rendah" },
    { kanji: "保つ", kana: "たもつ", correct: "menyimpan" },
    { kanji: "定期的", kana: "ていきてき", correct: "Secara teratur" },
    { kanji: "測定", kana: "そくてい", correct: "pengukuran" },
    { kanji: "結果", kana: "けっか", correct: "hasil" },
    { kanji: "食品衛生法", kana: "しょくひんえいせいほう", correct: "UU Sanitasi Pangan" },
    { kanji: "賞味期限", kana: "しようきげん", correct: "tanggal habis tempo" },
    { kanji: "賞味期限", kana: "しょうみきげん", correct: "tanggal habis tempo" },
    { kanji: "消費期限", kana: "しょうひきげん", correct: "tanggal habis tempo" },
    { kanji: "加工食品", kana: "かこうしょくひん", correct: "makanan olahan" },
    { kanji: "企業", kana: "きぎょう", correct: "perusahaan" },
    { kanji: "未開封", kana: "みかいふう", correct: "Belum dibuka" }
  ],
  31: [
    { kanji: "納品", kana: "のうひん", correct: "pengiriman bahan" },
    { kanji: "下処理", kana: "したしょり", correct: "persiapan" },
    { kanji: "工夫", kana: "くふ", correct: "kecerdikan" },
    { kanji: "解凍", kana: "かいとう", correct: "Pencairan" },
    { kanji: "加温", kana: "かおん", correct: "Pemanasan" },
    { kanji: "自然", kana: "しぜん", correct: "alami" },
    { kanji: "水道", kana: "すいどう", correct: "persediaan air,air PAM" }
  ],
  32: [
    { kanji: "汁", kana: "しる", correct: "cairan" },
    { kanji: "ドリップ", kana: "ドリップ", correct: "menetes" },
    { kanji: "トレー", kana: "トレー", correct: "baki,nampan" },
    { kanji: "網目トレー", kana: "あまみトレー", correct: "nampan jaring" },
    { kanji: "排水", kana: "はいすい", correct: "drainase,saluran pembuangan" },
    { kanji: "密閉", kana: "みっぺい", correct: "tertutup" },
    { kanji: "移し替えて", kana: "うつしかえて", correct: "pindahkan itu" },
    { kanji: "固形", kana: "こけい", correct: "padat" },
    { kanji: "ペースト", kana: "ペースト", correct: "tempel" },
    { kanji: "劣化", kana: "れっか", correct: "kemerosotan,menurun" },
    { kanji: "適正濃度", kana: "てきせいのうど", correct: "konsentrasi yang sesuai" },
    { kanji: "食塩水", kana: "しょくえんすい", correct: "larutan garam" },
    { kanji: "工程", kana: "こうてい", correct: "proses" },
    { kanji: "選別", kana: "せんべつ", correct: "penyortiran" },
    { kanji: "分別", kana: "ぶんべつ", correct: "penyortiran" },
    { kanji: "裁断", kana: "さいだん", correct: "pemotongan" },
    { kanji: "魚のウロコ", kana: "さかなのウロコ", correct: "sisik ikan" },
    { kanji: "確実", kana: "かくじつ", correct: "kepastian" },
    { kanji: "廃棄する", kana: "はいきする", correct: "membuang" },
    { kanji: "骨", kana: "ほね", correct: "tulang" },
    { kanji: "製造", kana: "せいぞう", correct: "produksi" },
    { kanji: "細断", kana: "さいだん", correct: "pencacahan" },
    { kanji: "混合", kana: "こんごう", correct: "pencampuran" },
    { kanji: "成型", kana: "せいけい", correct: "pencetakan" },
    { kanji: "配管", kana: "はいかん", correct: "perpipaan" }
  ],
  33: [
    { kanji: "物質", kana: "ぶっしつ", correct: "bahan" },
    { kanji: "加熱殺菌", kana: "かねつさっきん", correct: "sterilisasi panas" },
    { kanji: "消化", kana: "しょうか", correct: "pencernaan" },
    { kanji: "設定", kana: "せってい", correct: "pengaturan" },
    { kanji: "中心温度", kana: "ちゅうしんおんど", correct: "temperatur inti" },
    { kanji: "細菌", kana: "さいきん", correct: "bakteri" },
    { kanji: "かたまり", kana: "かたまり", correct: "gumpalan" },
    { kanji: "確かめます", kana: "たしかめます", correct: "akan saya periksa" },
    { kanji: "冷却", kana: "れいきゃく", correct: "pendinginan" }
  ],
  34: [
    { kanji: "冷える", kana: "ひえる", correct: "dingin" },
    { kanji: "増える", kana: "ふえる", correct: "meningkatkan" },
    { kanji: "具大的", kana: "ぐだいてき", correct: "secara khusus" },
    { kanji: "損なわない", kana: "そこなわない", correct: "tidak merusak" },
    { kanji: "次亜塩素酸ナトリウム", kana: "じあえんそさん", correct: "natrium hipoklorit" },
    { kanji: "冷凍", kana: "れいとう", correct: "beku" },
    { kanji: "保存性", kana: "ほぞんせい", correct: "umur penyimpanan" },
    { kanji: "生鮮", kana: "せいせん", correct: "segar" },
    { kanji: "凍結", kana: "とうけつ", correct: "beku" },
    { kanji: "硬さ", kana: "かたさ", correct: "kekerasan" },
    { kanji: "弾力", kana: "だんりょく", correct: "elastisitas" },
    { kanji: "食感", kana: "しょっかん", correct: "tekstur" },
    { kanji: "風味", kana: "ふうみ", correct: "rasa" },
    { kanji: "短時間", kana: "たんじかん", correct: "waktu singkat" },
    { kanji: "急速", kana: "きゅうそく", correct: "cepat" }
  ],
  35: [
    { kanji: "充填", kana: "じゅうてん", correct: "isian" },
    { kanji: "包装", kana: "ほうそう", correct: "kemasan" },
    { kanji: "検査", kana: "けんさ", correct: "inspeksi,pengecekan" },
    { kanji: "選別", kana: "せんべつ", correct: "penyortiran" },
    { kanji: "殺菌", kana: "さっきん", correct: "sterilisasi" },
    { kanji: "危害要因", kana: "きがいよういん", correct: "faktor bahaya" },
    { kanji: "ボルト", kana: "ボルト", correct: "baut" },
    { kanji: "キャップ", kana: "キャップ", correct: "tutup" },
    { kanji: "内側", kana: "うちがわ", correct: "didalam" },
    { kanji: "出荷", kana: "しゅっか", correct: "pengiriman" },
    { kanji: "印字します", kana: "いんじします", correct: "mencetak" },
    { kanji: "数字", kana: "すうじ", correct: "angka" },
    { kanji: "ミス", kana: "ミス", correct: "kesalahan" },
    { kanji: "発生", kana: "はっせい", correct: "kejadian" },
    { kanji: "穴", kana: "あな", correct: "lubang" },
    { kanji: "空気", kana: "くうき", correct: "udara" },
    { kanji: "もれたり", kana: "もれたり", correct: "Bocor" },
    { kanji: "中身", kana: "なかみ", correct: "isi" },
    { kanji: "金属探知機", kana: "きんぞくたんちき", correct: "detektor logam" },
    { kanji: "硬質異物", kana: "こうしついぶつ", correct: "benda asing yang keras" },
    { kanji: "管理", kana: "かんり", correct: "pengelolaan" },
    { kanji: "テストピース", kana: "テストピース", correct: "Benda uji" },
    { kanji: "正常", kana: "せいじょう", correct: "normal" }
  ],
  36: [
    { kanji: "機能", kana: "きのう", correct: "fungsi" },
    { kanji: "時点", kana: "じてん", correct: "titik waktu" },
    { kanji: "X線異物検出器", kana: "Xせんいぶつけんしゅつき", correct: "detektor benda asing sinar-X" },
    { kanji: "数量", kana: "すうりょう", correct: "kuantitas" },
    { kanji: "不足", kana: "ふそく", correct: "kekurangan" },
    { kanji: "形状不良品", kana: "けいじょうふりょうひん", correct: "Bentuk produk cacat" },
    { kanji: "プラスチック", kana: "プラスチック", correct: "plastik" },
    { kanji: "頼る", kana: "たよる", correct: "mengandalkan" },
    { kanji: "微生物検査", kana: "びせいぶつけんさ", correct: "pengujian mikroba" },
    { kanji: "法律", kana: "ほうりつ", correct: "hukum" },
    { kanji: "義務", kana: "ぎむ", correct: "wajib" },
    { kanji: "項目", kana: "こうもく", correct: "barang" },
    { kanji: "自主的", kana: "じしゅてき", correct: "Sukarela" },
    { kanji: "配送", kana: "はいそう", correct: "pengiriman" },
    { kanji: "サンプル", kana: "サンプル", correct: "Sampel" },
    { kanji: "クレーム", kana: "クレーム", correct: "mengeklaim" },
    { kanji: "時期", kana: "じき", correct: "musim" }
  ],
  37: [
    { kanji: "一定の割合", kana: "いっていのわりあい", correct: "persentase tertentu" },
    { kanji: "抜き出す", kana: "ぬきだす", correct: "mengeluarkan" },
    { kanji: "保管参照", kana: "ほかんさんしょう", correct: "referensi penyimpanan" },
    { kanji: "輸送中", kana: "ゆそうちゅう", correct: "sedang transit" },
    { kanji: "品質", kana: "ひんしつ", correct: "kualitas" },
    { kanji: "劣化", kana: "れっか", correct: "kemerosotan" },
    { kanji: "特別", kana: "とくべつ", correct: "spesial" },
    { kanji: "仕組み", kana: "しくみ", correct: "struktur" },
    { kanji: "調べる", kana: "しらべる", correct: "menyelidiki" },
    { kanji: "含む", kana: "ふくむ", correct: "termasuk" },
    { kanji: "分析", kana: "ぶんせき", correct: "analisis" },
    { kanji: "管理基準", kana: "かんりきじゅん", correct: "standar manajemen" },
    { kanji: "実行", kana: "じっこう", correct: "eksekusi" },
    { kanji: "監視", kana: "かんし", correct: "pengawasan" },
    { kanji: "原則", kana: "げんそく", correct: "prinsip" },
    { kanji: "従って", kana: "したがって", correct: "sesuai" },
    { kanji: "運用される", kana: "うんようされる", correct: "dioperasikan" }
  ],
  38: [
    { kanji: "判断", kana: "はんだん", correct: "pertimbangan" },
    { kanji: "改善措置", kana: "かいぜんそち", correct: "langkah-langkah perbaikan" },
    { kanji: "逸脱", kana: "いつだつ", correct: "menyimpang" },
    { kanji: "検証方法", kana: "けんしょうほうほう", correct: "metode verifikasi" },
    { kanji: "除去", kana: "じょきょ", correct: "menghilangkan" },
    { kanji: "低減", kana: "ていげん", correct: "mengurangi" },
    { kanji: "有効", kana: "ゆうこう", correct: "efektif" },
    { kanji: "計画", kana: "けいかく", correct: "rencana" },
    { kanji: "記録", kana: "きろく", correct: "catatan" },
    { kanji: "内容", kana: "ないよう", correct: "isi" },
    { kanji: "文章", kana: "ぶんしょ", correct: "kalimat" },
    { kanji: "実際", kana: "じっさい", correct: "sebenarnya" }
  ],
  39: [
    { kanji: "惣菜", kana: "そうざい", correct: "lauk pauk" },
    { kanji: "加熱調理する", kana: "かねつちょうりする", correct: "memasak" },
    { kanji: "管理基準", kana: "かんりきじゅん", correct: "standar manajemen" },
    { kanji: "重要管理点", kana: "じゅうようかんりてん", correct: "titik kontrol penting" },
    { kanji: "代表的", kana: "だいひょうてき", correct: "umum" },
    { kanji: "具体的", kana: "ぐたいてき", correct: "secara khusus" },
    { kanji: "参照", kana: "さんしょう", correct: "referensi" }
  ],
  40: [
    { kanji: "加熱ゾーン", kana: "かねつゾーン", correct: "zona pemanasan" },
    { kanji: "通る", kana: "とおる", correct: "melewati" },
    { kanji: "速度", kana: "そくど", correct: "kecepatan" },
    { kanji: "調整", kana: "ちょうせい", correct: "pengaturan" },
    { kanji: "不足", kana: "ふそく", correct: "kekurangan" },
    { kanji: "廃棄する", kana: "はいきする", correct: "membuang" },
    { kanji: "実施した", kana: "じっしした", correct: "dilakukan" },
    { kanji: "管理手段", kana: "かんりしゅだん", correct: "langkah-langkah pengelolaan" },
    { kanji: "手順", kana: "てじゅん", correct: "prosedur" },
    { kanji: "あらかじめ", kana: "あらかじめ", correct: "di muka" },
    { kanji: "ハンバーグ", kana: "ハンバーグ", correct: "roti isi daging" },
    { kanji: "殺菌液の濃度", kana: "さっきんえきののうど", correct: "konsentrasi larutan sterilisasi" },
    { kanji: "計る", kana: "はかる", correct: "ukuran" },
    { kanji: "事実", kana: "じじつ", correct: "fakta" },
    { kanji: "絶対", kana: "ぜったい", correct: "mutlak" },
    { kanji: "修正する", kana: "しゅうせいする", correct: "memperbaiki" }
  ],
  43: [
    { kanji: "労働災害", kana: "ろうどうさいがい", correct: "kecelakaan industri" },
    { kanji: "経験", kana: "けいけん", correct: "pengalaman" },
    { kanji: "関係", kana: "かんけい", correct: "hubungan" },
    { kanji: "全て", kana: "すべて", correct: "semua" },
    { kanji: "未熟練作業者", kana: "みじゅくれんさぎょうしゃ", correct: "pekerja tidak terampil" },
    { kanji: "未満", kana: "みまん", correct: "kurang dari" },
    { kanji: "占める", kana: "しめる", correct: "menempati" },
    { kanji: "割合", kana: "わりあい", correct: "perbandingan" },
    { kanji: "慣れてない", kana: "なれてない", correct: "belum terbiasa" },
    { kanji: "気が付いてない", kana: "きがついてない", correct: "tidak menyadarinya" },
    { kanji: "多いじゅん", kana: "おおいじゅん", correct: "kebanyakan" },
    { kanji: "転倒", kana: "てんとう", correct: "jatuh" },
    { kanji: "はさまれ", kana: "はさまれ", correct: "terjepit" },
    { kanji: "巻き込まれ", kana: "まきこまれ", correct: "kelilit,terjepit" },
    { kanji: "切れる", kana: "きれる", correct: "terpotong" },
    { kanji: "擦れ", kana: "こすれ", correct: "menggosok" }
  ],
  44: [
    { kanji: "主な", kana: "おもな", correct: "utama" },
    { kanji: "つまずいたり", kana: "つまずいたり", correct: "tersandung" },
    { kanji: "滑る", kana: "すべる", correct: "licin" },
    { kanji: "打ったり", kana: "うったり", correct: "memukul" },
    { kanji: "折り", kana: "おり", correct: "patah" },
    { kanji: "骨", kana: "ほね", correct: "tulang" },
    { kanji: "コンベアのギア", kana: "コンベアのギア", correct: "roda gigi konveyor" },
    { kanji: "つぶれたり", kana: "つぶれたり", correct: "hancur" },
    { kanji: "はさまる", kana: "はさまる", correct: "terjepit" },
    { kanji: "包丁", kana: "ほうちょう", correct: "pisau" },
    { kanji: "詰まって手", kana: "つまってて", correct: "tanganku tersangkut" },
    { kanji: "階段", kana: "かいだん", correct: "tangga" },
    { kanji: "はしご", kana: "はしご", correct: "tangga" },
    { kanji: "脚立", kana: "きゃたつ", correct: "tangga segitiga" },
    { kanji: "捻挫する", kana: "ねんざする", correct: "keseleo" },
    { kanji: "オーブン", kana: "オーブン", correct: "oven" },
    { kanji: "全身", kana: "ぜんしん", correct: "seluruh tubuh" }
  ],
  45: [
    { kanji: "腰痛", kana: "ようつう", correct: "nyeri punggung bawah" },
    { kanji: "繰り返す", kana: "くりかえす", correct: "mengulang" },
    { kanji: "熱中症", kana: "ねっちゅうしょう", correct: "struk akibat panas" },
    { kanji: "湿度", kana: "しつど", correct: "kelembaban" },
    { kanji: "体内", kana: "たいない", correct: "didalam tubuh" },
    { kanji: "水分", kana: "すいぶん", correct: "kelembaban" },
    { kanji: "塩分", kana: "えんぶん", correct: "garam" },
    { kanji: "崩れる", kana: "くずれる", correct: "runtuh" },
    { kanji: "体温調節", kana: "たいおんちょうせつ", correct: "pengaturan suhu tubuh" },
    { kanji: "激突", kana: "げきとつ", correct: "bentrokan,tabrakan" },
    { kanji: "目標", kana: "もくてき", correct: "hasil" },
    { kanji: "活動", kana: "かつどう", correct: "aktivitas" }
  ],
  46: [
    { kanji: "不要なもの", kana: "ふようなもの", correct: "tidak perlu" },
    { kanji: "状態", kana: "じょうたい", correct: "situasi" },
    { kanji: "保ちます", kana: "たもちます", correct: "menjaga" },
    { kanji: "動線", kana: "どうせん", correct: "garis arus" },
    { kanji: "枠の中", kana: "わくのなか", correct: "didalam bingkai" },
    { kanji: "床のテープ", kana: "ゆかのテープ", correct: "pita lantai" },
    { kanji: "沿って", kana: "そって", correct: "bersama" },
    { kanji: "減ります", kana: "へります", correct: "berkurang" },
    { kanji: "つながります", kana: "つながります", correct: "terhubung" },
    { kanji: "感染症", kana: "かんせんしょう", correct: "Infeksi" },
    { kanji: "役立ちます", kana: "やくだちます", correct: "bermanfaat,membantu" },
    { kanji: "長袖", kana: "ながそで", correct: "lengan panjang" },
    { kanji: "袖口", kana: "そでぐち", correct: "manset" },
    { kanji: "袖", kana: "そで", correct: "lengan baju" },
    { kanji: "まくり上げない", kana: "まくりあげない", correct: "Jangan menggulungnya" }
  ],
  47: [
    { kanji: "安全保護具", kana: "あんぜんほごぐ", correct: "peralatan perlindungan keselamatan" },
    { kanji: "高所場所", kana: "こうしょばしょ", correct: "tempat yang tinggi" },
    { kanji: "薬品", kana: "やくひん", correct: "obat" },
    { kanji: "微粉", kana: "びふん", correct: "bubuk halus" },
    { kanji: "高圧洗浄", kana: "こうあつせんじょう", correct: "pencucian bertekanan tinggi" },
    { kanji: "液体", kana: "えきたい", correct: "cairan" },
    { kanji: "騒音", kana: "そうおん", correct: "kebisikan" },
    { kanji: "難聴", kana: "なんちょう", correct: "gangguan pendengaran" },
    { kanji: "耐熱のぬね", kana: "たいねつのぬね", correct: "Dogwood tahan panas" },
    { kanji: "繊維", kana: "せんい", correct: "serat" },
    { kanji: "編み", kana: "あみ", correct: "rajutan" },
    { kanji: "耐切創", kana: "たいせっそう", correct: "Resistensi terhadap potongan" },
    { kanji: "つま先", kana: "つまさき", correct: "jari kaki" },
    { kanji: "かかとに", kana: "かかとに", correct: "dengan tumit" },
    { kanji: "鋼板", kana: "こうばん", correct: "pelat baja" },
    { kanji: "装着", kana: "そうちゃく", correct: "lampiran" },
    { kanji: "ステンレス鋼", kana: "ステンレスこう", correct: "besi tahan karat" },
    { kanji: "耐油", kana: "たいゆ", correct: "tahan minyak" },
    { kanji: "靴底", kana: "くつぞこ", correct: "sol sepatu" },
    { kanji: "上部", kana: "じょうぶ", correct: "bagian atas" }
  ],
  48: [
    { kanji: "作業手順", kana: "さぎょうてじゅん", correct: "prosedur kerja" },
    { kanji: "基本的な", kana: "きほんてきな", correct: "pada dasarnya" },
    { kanji: "通路", kana: "つうろ", correct: "lorong" },
    { kanji: "横断方法", kana: "おうだんほうほう", correct: "metode penyeberangan" },
    { kanji: "目を合わせて", kana: "めをあわせて", correct: "mengkombinasikan penglihatan" },
    { kanji: "くぐらない", kana: "くぐらない", correct: "Jangan lewati" },
    { kanji: "指差呼称", kana: "しさこしょう", correct: "menunjuk dan memanggil" },
    { kanji: "共同", kana: "きょうどう", correct: "Persendian" },
    { kanji: "よそ見", kana: "よそみ", correct: "mengalihkan pandangan" },
    { kanji: "無駄話", kana: "ムダはなし", correct: "pembicaraan kosong" }
  ],
  49: [
    { kanji: "信号", kana: "しんごう", correct: "sinyal" },
    { kanji: "標識", kana: "ひょうしき", correct: "tanda" },
    { kanji: "器具", kana: "きぐ", correct: "peralatan" },
    { kanji: "目的", kana: "もくてき", correct: "tujuan" },
    { kanji: "行います", kana: "おこないます", correct: "menerapkan" },
    { kanji: "理解", kana: "りかい", correct: "memahami" },
    { kanji: "示したもの", kana: "しめしたもの", correct: "apa yang ditampilkan" },
    { kanji: "補足資料", kana: "ほそくしりょう", correct: "materi tambahan" },
    { kanji: "参照", kana: "さんしょう", correct: "referensi" },
    { kanji: "丁寧", kana: "ていねい", correct: "sopan" },
    { kanji: "落ち着いて", kana: "おちついて", correct: "tenang" },
    { kanji: "無料", kana: "むり", correct: "tidak memunkinkan" },
    { kanji: "始業前点検", kana: "しぎょうまえてんけん", correct: "memeriksa sebelum mulai bekerja" },
    { kanji: "異常", kana: "いじょう", correct: "kelainan" },
    { kanji: "はさまる", kana: "はさまる", correct: "tercepit" },
    { kanji: "振動", kana: "しんどう", correct: "getaran" },
    { kanji: "部品", kana: "ぶひん", correct: "bagian" }
  ],
  50: [
    { kanji: "ネジ", kana: "ネジ", correct: "baut" },
    { kanji: "動作", kana: "どうさ", correct: "gerakan" },
    { kanji: "正常", kana: "せいじょう", correct: "normal" },
    { kanji: "点灯", kana: "てんとう", correct: "menyala" },
    { kanji: "消灯", kana: "消灯", correct: "lampu padam" },
    { kanji: "停止", kana: "ていし", correct: "Berhenti" },
    { kanji: "刃先", kana: "はさき", correct: "ujung bilah" },
    { kanji: "スクリュー", kana: "スクリュー", correct: "baut" },
    { kanji: "回転", kana: "かいてん", correct: "memutar" },
    { kanji: "詰まったもの", kana: "つまったもの", correct: "barang tersumbat" },
    { kanji: "取り除く", kana: "とりのぞく", correct: "mengambil" },
    { kanji: "操作盤", kana: "そうさばん", correct: "papan operasi" }
  ],
  51: [
    { kanji: "安全装置", kana: "あんぜんそうち", correct: "perangkat keamanan" },
    { kanji: "扉", kana: "とびら", correct: "pintu" },
    { kanji: "自動的", kana: "じどうてき", correct: "secara otomatis" },
    { kanji: "仕組み", kana: "しくみ", correct: "struktur" },
    { kanji: "フェールセーフ", kana: "フェールセーフ", correct: "gagal keamanan" },
    { kanji: "電源", kana: "でんげん", correct: "sumber daya listrik" },
    { kanji: "チェーン", kana: "チェーン", correct: "rantai" },
    { kanji: "故障対応中", kana: "こしょうたいおうちゅう", correct: "Pemecahan masalah sedang berlangsung" },
    { kanji: "ぶら下げて", kana: "ぶらさげて", correct: "gantung itu" },
    { kanji: "うっかり", kana: "うっかり", correct: "secara tidak sengaja" },
    { kanji: "フールプルーフ", kana: "フールプルーフ", correct: "bukti bodoh" },
    { kanji: "メンテナンス", kana: "メンテナンス", correct: "pemeliharaan" },
    { kanji: "安定", kana: "あんてい", correct: "stabil" },
    { kanji: "整備", kana: "せいび", correct: "Pemeliharaan" },
    { kanji: "生産", kana: "せいさん", correct: "produksi" }
  ],
  52: [
    { kanji: "洗剤", kana: "せんざい", correct: "deterjen" },
    { kanji: "薬剤", kana: "やくざい", correct: "obat" },
    { kanji: "塩素系", kana: "えんそけい", correct: "diklorinasi" },
    { kanji: "酸性洗剤", kana: "さんせいせんざい", correct: "deterjen asam" },
    { kanji: "混ぜる", kana: "まぜる", correct: "mencampur" },
    { kanji: "同時に", kana: "どうじに", correct: "pada saat yang sama" },
    { kanji: "有毒", kana: "ゆうどく", correct: "beracun" },
    { kanji: "異常事態", kana: "いじょうじたい", correct: "Situasi tidak normal" },
    { kanji: "対応", kana: "たいおう", correct: "korespondensi" },
    { kanji: "応じて", kana: "おうじて", correct: "bergantung kepada" },
    { kanji: "緊急", kana: "きんきゅう", correct: "keadaan darurat" },
    { kanji: "勝手に", kana: "かってに", correct: "sewenang-wenang" },
    { kanji: "行动", kana: "こうどう", correct: "tindakan" },
    { kanji: "倒れる", kana: "たおれる", correct: "jatuh" }
  ],
  53: [
    { kanji: "あわてて", kana: "あわてて", correct: "terburu-buru" },
    { kanji: "助ける", kana: "たすける", correct: "membantu" },
    { kanji: "二次災害", kana: "にじさいがい", correct: "Bencana sekunder" },
    { kanji: "日頃", kana: "ひごろ", correct: "setiap hari" },
    { kanji: "訓練", kana: "くんれん", correct: "pelatihan" },
    { kanji: "火災", kana: "かさい", correct: "api" },
    { kanji: "避難訓練", kana: "ひなんくんれん", correct: "Latihan evakuasi" },
    { kanji: "レバー", kana: "レバー", correct: "tuas" },
    { kanji: "ぐらぐらする", kana: "ぐらぐらする", correct: "goyangan" },
    { kanji: "点滅", kana: "てんめつ", correct: "berkedip" },
    { kanji: "身につけて", kana: "みにつけて", correct: "pakai itu" }
  ],
  54: [
    { kanji: "事例", kana: "じれい", correct: "studi kasus" },
    { kanji: "学ぶ", kana: "まなぶ", correct: "mempelajari" },
    { kanji: "社内", kana: "しゃない", correct: "Di dalam perusahaan" },
    { kanji: "身近", kana: "みじか", correct: "akrab,familiar" },
    { kanji: "社外", kana: "しゃがい", correct: "Di luar perusahaan" },
    { kanji: "覚える", kana: "おぼえる", correct: "mengingat" },
    { kanji: "ヒヤリハット", kana: "ヒヤリハット", correct: "hampir kecelakaan" },
    { kanji: "軽い", kana: "かるい", correct: "ringan" },
    { kanji: "件", kana: "けん", correct: "kasus" },
    { kanji: "法則", kana: "ほうそく", correct: "hukum" },
    { kanji: "ハインリッヒ", kana: "ハインリッヒ", correct: "heinrich" }
  ],
  55: [
    { kanji: "体験", kana: "たいけん", correct: "pengalaman" },
    { kanji: "全員", kana: "ぜんいん", correct: "semua orang" },
    { kanji: "共有", kana: "きょうゆう", correct: "membagikan" },
    { kanji: "改善", kana: "かいぜん", correct: "peningkatan" },
    { kanji: "進む", kana: "すすむ", correct: "maju" },
    { kanji: "実際", kana: "じっさい", correct: "sebenarnya" },
    { kanji: "潜在的", kana: "せんざいてき", correct: "potensi" },
    { kanji: "力", kana: "ちから", correct: "kekuatan" },
    { kanji: "文字", kana: "もじ", correct: "huruf" },
    { kanji: "感電する", kana: "かんでんする", correct: "sengatan listrik" },
    { kanji: "酸欠になる", kana: "さんけつになる", correct: "kekurangan oksigen" },
    { kanji: "有害物にやられる", kana: "ゆうがいぶつにやられる", correct: "terserang zat-zat berbahaya" },
    { kanji: "くずれる", kana: "くずれる", correct: "hancur" },
    { kanji: "爆発", kana: "ばくはつ", correct: "ledakan" },
    { kanji: "漏れる", kana: "もれる", correct: "bocor" }
  ],
  56: [
    { kanji: "姿勢", kana: "しせい", correct: "sikap" },
    { kanji: "イラスト", kana: "イラスト", correct: "ilustrasi" },
    { kanji: "示した", kana: "しめした", correct: "diindikasikan" },
    { kanji: "警戒", kana: "けいかい", correct: "kewaspadaan" },
    { kanji: "積まれた", kana: "つまれた", correct: "menumpuk" },
    { kanji: "煮物", kana: "にもの", correct: "makanan rebus" },
    { kanji: "ガスコンロ", kana: "ガスコンロ", correct: "Tungku gas" },
    { kanji: "室内", kana: "しつない", correct: "dalam" },
    { kanji: "トレー", kana: "トレー", correct: "baki" },
    { kanji: "移動", kana: "いどう", correct: "bergerak" },
    { kanji: "拭き取って", kana: "ふきとって", correct: "bersihkan" }
  ],
  57: [
    { kanji: "両手", kana: "りょうて", correct: "kedua tangan" },
    { kanji: "通路", kana: "つうろ", correct: "lorong,jalan" },
    { kanji: "空箱", kana: "からばこ", correct: "kotak kosong" },
    { kanji: "つまずき", kana: "つまずき", correct: "tersandung" },
    { kanji: "転倒", kana: "てんとう", correct: "jatuh" },
    { kanji: "重ねて", kana: "かさねて", correct: "tumpuk" },
    { kanji: "数", kana: "かず", correct: "jumlah" },
    { kanji: "突然", kana: "とつぜん", correct: "tiba-tiba" }
  ],
  58: [
    { kanji: "引っ掛かって", kana: "引っ掛かって", correct: "tersangkut,terjepit" },
    { kanji: "除去", kana: "じょきょ", correct: "pemindahan" },
    { kanji: "確実", kana: "かくじつ", correct: "memastikan" },
    { kanji: "原因", kana: "げんいん", correct: "penyebab" },
    { kanji: "対策", kana: "たいさく", correct: "penanganan" },
    { kanji: "滑り", kana: "すべり", correct: "licin" },
    { kanji: "加工する", kana: "かこうする", correct: "proses" },
    { kanji: "落ちる", kana: "おちる", correct: "jatuh kebawah" },
    { kanji: "棚", kana: "たな", correct: "rak" },
    { kanji: "脚立", kana: "きゃたつ", correct: "anak tangga" }
  ],
  60: [
    { kanji: "止金具", kana: "とめかなぐ", correct: "pengikat,pengunci" },
    { kanji: "鉄板", kana: "てっぱん", correct: "plat besi" },
    { kanji: "作業台", kana: "さぎょうだい", correct: "meja kerja" },
    { kanji: "移そう", kana: "うつそう", correct: "memindahkan" },
    { kanji: "素手で", kana: "すで", correct: "dengan tangan kosong" },
    { kanji: "直後", kana: "ちょくご", correct: "segera setelah" },
    { kanji: "鍋", kana: "なべ", correct: "panci" },
    { kanji: "釜", kana: "かま", correct: "ketel" }
  ],
  61: [
    { kanji: "腰痛", kana: "ようつう", correct: "nyeri punggung bawah" },
    { kanji: "感じる", kana: "かんじる", correct: "merasakan" },
    { kanji: "不安定", kana: "ふ不安てい", correct: "tidak stabil" },
    { kanji: "膝", kana: "ひざ", correct: "lutut" },
    { kanji: "曲げて", kana: "まげて", correct: "membengkokkan" },
    { kanji: "抱えて", kana: "かかえて", correct: "tahan, peluk" },
    { kanji: "伸ばす", kana: "のばす", correct: "menggeliat, memanjangkan" },
    { kanji: "生あん工程", kana: "せいあんこうてい", correct: "proses pasta kacang mentah" },
    { kanji: "ホッパー", kana: "ホッパー", correct: "gerbong" },
    { kanji: "豆", kana: "まめ", correct: "kacang polong" },
    { kanji: "計量", kana: "けいりょう", correct: "pengukuran" },
    { kanji: "繰り返し", kana: "くりかえし", correct: "pengulangan" },
    { kanji: "ふらつき", kana: "ふらつき", correct: "sakit kepala ringan" },
    { kanji: "診断", kana: "しんだん", correct: "diagnosa" },
    { kanji: "汗", kana: "あせ", correct: "keringat" }
  ],
  62: [
    { kanji: "安静", kana: "あんせい", correct: "istirahat" },
    { kanji: "緩める", kana: "ゆるめる", correct: "melonggarkan" },
    { kanji: "脇の下", kana: "わきのした", correct: "ketiak" },
    { kanji: "足の付け根", kana: "あしの付け根", correct: "pangkal kaki" },
    { kanji: "スポーツドリンク", kana: "スポーツドリンク", correct: "minuman olahraga" },
    { kanji: "激突", kana: "げきとつ", correct: "Bentrokan,tabrakan" },
    { kanji: "一時停止", kana: "いちじていし", correct: "berhenti sebentar" },
    { kanji: "運転者", kana: "うんてんしゃ", correct: "pengemudi" }
  ],
  63: [
    { kanji: "立入禁止", kana: "たちいりきんし", correct: "larangan masuk" },
    { kanji: "開放厳禁", kana: "かいほうげんきん", correct: "dilarang keras untuk dibuka" },
    { kanji: "点検中", kana: "てんけんちゅう", correct: "sedang diperiksa" },
    { kanji: "スイッチをいれるな", kana: "スイッチをいれるな", correct: "jangan hidupkan saklarnya" },
    { kanji: "手を触れるな", kana: "てをふれるな", correct: "Jangan sentuh" },
    { kanji: "はさまれ注意", kana: "はさまれちゅうい", correct: "Hati-hati terjepit" },
    { kanji: "火傷注意", kana: "やけどちゅうい", correct: "Hati-hati terhadap luka bakar" },
    { kanji: "高温注意", kana: "こうおんちゅうい", correct: "Hati-hati terhadap suhu tinggi" }
  ],
  64: [
    { kanji: "足元注意", kana: "あしもとちゅうい", correct: "Perhatikan langkahmu" },
    { kanji: "危険転倒注意", kana: "きけんてんとうちゅうい", correct: "Bahaya terjatuh" },
    { kanji: "開口部注意", kana: "かいこうぶちゅうい", correct: "Hati-hati dengan bukaan" },
    { kanji: "転落注意", kana: "てんらくちゅうい", correct: "Hati-hati agar tidak jatuh" },
    { kanji: "切断注意", kana: "せつだんちゅうい", correct: "Hati-hati dalam memotong" },
    { kanji: "回転物に手をだすな", kana: "かいてんものてをだすな", correct: "Jangan menyentuh benda berputar" },
    { kanji: "感電注意", kana: "かんでんちゅうい", correct: "Hati-hati terhadap sengatan listrik" },
    { kanji: "頭上注意", kana: "ずじょうちゅうい", correct: "perhatikan kepalamu" }
  ],
  65: [
    { kanji: "ゴーグル着用", kana: "ゴーグルちゃくよう", correct: "Mengenakan kacamata" },
    { kanji: "保護メガネ着用", kana: "ほごめがねちゃくよう", correct: "Kenakan kacamata pengaman" },
    { kanji: "非常口", kana: "ひじょうぐち", correct: "pintu darurat" },
    { kanji: "消火器", kana: "しょうかき", correct: "alat pemadam api" }
  ]
};