const irodoriKanjiData = [
  { kanji: "魚", kana: "さかな", answers: ["Ikan", "Daging", "Telur", "Air"], correct: "Ikan" },
  { kanji: "肉", kana: "にく", answers: ["Daging", "Ikan", "Telur", "Sayuran"], correct: "Daging" },
  { kanji: "卵", kana: "たまご", answers: ["Telur", "Daging", "Ikan", "Nasi"], correct: "Telur" },
  { kanji: "水", kana: "みず", answers: ["Air", "Api", "Tanah", "Angin"], correct: "Air" },
  { kanji: "食べます", kana: "たべます", answers: ["Makan", "Minum", "Tidur", "Pergi"], correct: "Makan" },
  { kanji: "飲みます", kana: "のみます", answers: ["Minum", "Makan", "Baca", "Lihat"], correct: "Minum" },
  { kanji: "大きい", kana: "おおきい", answers: ["Besar", "Kecil", "Baru", "Lama"], correct: "Besar" },
  { kanji: "小さい", kana: "ちいさい", answers: ["Kecil", "Besar", "Pendek", "Luas"], correct: "Kecil" },
  { kanji: "新しい", kana: "あたらしい", answers: ["Baru", "Lama", "Mahal", "Murah"], correct: "Baru" },
  { kanji: "古い", kana: "ふるい", answers: ["Lama, usang", "Baru", "Jelek", "Bagus"], correct: "Lama, usang" },
  { kanji: "~時", kana: "~じ", answers: ["jam", "menit", "detik", "setengah"], correct: "jam" },
  { kanji: "~分", kana: "~ふん、ぷん、ぶん", answers: ["menit", "jam", "hari", "bulan"], correct: "menit" },
  { kanji: "~半", kana: "~はん", answers: ["setengah", "seperempat", "satu", "seluruh"], correct: "setengah" },
  { kanji: "月曜日", kana: "げつようび", answers: ["Senin", "Selasa", "Rabu", "Kamis"], correct: "Senin" },
  { kanji: "火曜日", kana: "かようび", answers: ["Selasa", "Senin", "Rabu", "Jumat"], correct: "Selasa" },
  { kanji: "水曜日", kana: "すいようび", answers: ["Rabu", "Selasa", "Kamis", "Sabtu"], correct: "Rabu" },
  { kanji: "木曜日", kana: "もくようび", answers: ["Kamis", "Rabu", "Jumat", "Minggu"], correct: "Kamis" },
  { kanji: "金曜日", kana: "きんようび", answers: ["Jumat", "Kamis", "Sabtu", "Selasa"], correct: "Jumat" },
  { kanji: "土曜日", kana: "どようび", answers: ["Sabtu", "Jumat", "Minggu", "Senin"], correct: "Sabtu" },
  { kanji: "日曜日", kana: "にちようび", answers: ["Minggu", "Sabtu", "Senin", "Rabu"], correct: "Minggu" },
  { kanji: "言います", kana: "いいます", answers: ["Berkata", "Mendengar", "Menulis", "Pergi"], correct: "Berkata" },
  { kanji: "話します", kana: "はなします", answers: ["Berbicara", "Berlari", "Berenang", "Bertemu"], correct: "Berbicara" },
  { kanji: "読みます", kana: "よみます", answers: ["Membaca", "Menulis", "Melihat", "Mendengar"], correct: "Membaca" },
  { kanji: "見ます", kana: "みます", answers: ["Melihat", "Mendengar", "Berkata", "Membeli"], correct: "Melihat" },
  { kanji: "聞きます", kana: "ききます", answers: ["Mendengarkan", "Melihat", "Berbicara", "Menulis"], correct: "Mendengarkan" },
  { kanji: "書きます", kana: "かきます", answers: ["Menulis", "Membaca", "Mengirim", "Membuat"], correct: "Menulis" },
  { kanji: "一", kana: "いち", answers: ["Satu", "Dua", "Tiga", "Empat"], correct: "Satu" },
  { kanji: "二", kana: "に", answers: ["Dua", "Satu", "Tiga", "Lima"], correct: "Dua" },
  { kanji: "三", kana: "さん", answers: ["Tiga", "Satu", "Dua", "Enam"], correct: "Tiga" },
  { kanji: "四", kana: "よん、し", answers: ["Empat", "Tiga", "Lima", "Enam"], correct: "Empat" },
  { kanji: "五", kana: "ご", answers: ["Lima", "Empat", "Enam", "Tujuh"], correct: "Lima" },
  { kanji: "六", kana: "ろく", answers: ["Enam", "Lima", "Tujuh", "Delapan"], correct: "Enam" },
  { kanji: "七", kana: "なな、しち", answers: ["Tujuh", "Enam", "Delapan", "Sembilan"], correct: "Tujuh" },
  { kanji: "八", kana: "はち", answers: ["Delapan", "Tujuh", "Sembilan", "Sepuluh"], correct: "Delapan" },
  { kanji: "九", kana: "きゅう", answers: ["Sembilan", "Delapan", "Sepuluh", "Satu"], correct: "Sembilan" },
  { kanji: "+", kana: "じゅう", answers: ["Sepuluh", "Sembilan", "Seratus", "Satu"], correct: "Sepuluh" },
  { kanji: "~年", kana: "~ねん", answers: ["tahun", "bulan", "tanggal", "jam"], correct: "tahun" },
  { kanji: "~月", kana: "~がつ", answers: ["bulan", "tahun", "minggu", "hari"], correct: "bulan" },
  { kanji: "~日", kana: "~にち", answers: ["~ tanggal", "bulan", "tahun", "jam"], correct: "~ tanggal" },
  { kanji: "東", kana: "ひがし", answers: ["Timur", "Barat", "Selatan", "Utara"], correct: "Timur" },
  { kanji: "西", kana: "にし", answers: ["Barat", "Timur", "Utara", "Selatan"], correct: "Barat" },
  { kanji: "南", kana: "みなみ", answers: ["Selatan", "Utara", "Timur", "Barat"], correct: "Selatan" },
  { kanji: "北", kana: "きた", answers: ["Utara", "Selatan", "Barat", "Timur"], correct: "Utara" },
  { kanji: "~口", kana: "〜ぐち", answers: ["~ pintu", "lubang", "jalan", "arah"], correct: "~ pintu" },
  { kanji: "東口", kana: "ひがしぐち", answers: ["Pintu timur", "Pintu barat", "Pintu utara", "Pintu selatan"], correct: "Pintu timur" },
  { kanji: "西口", kana: "にしぐち", answers: ["Pintu barat", "Pintu timur", "Pintu selatan", "Pintu utara"], correct: "Pintu barat" },
  { kanji: "南口", kana: "みなみぐち", answers: ["Pintu selatan", "Pintu utara", "Pintu timur", "Pintu barat"], correct: "Pintu selatan" },
  { kanji: "北口", kana: "きたぐち", answers: ["Pintu utara", "Pintu selatan", "Pintu barat", "Pintu timur"], correct: "Pintu utara" },
  { kanji: "買います", kana: "かいます", answers: ["Membeli", "Menjual", "Melihat", "Membuat"], correct: "Membeli" },
  { kanji: "買い物", kana: "かいもの", answers: ["Belanja", "Makanan", "Minuman", "Barang"], correct: "Belanja" },
  { kanji: "お金", kana: "おかね", answers: ["Uang", "Emas", "Perak", "Kaya"], correct: "Uang" },
  { kanji: "~円", kana: "~えん", answers: ["~ yen", "rupiah", "dolar", "angka"], correct: "~ yen" },
  { kanji: "百", kana: "ひゃく", answers: ["10", "100", "1,000", "10,000"], correct: "100" },
  { kanji: "千", kana: "せん", answers: ["100", "1,000", "10,000", "5,000"], correct: "1,000" },
  { kanji: "万", kana: "まん", answers: ["1,000", "10,000", "100,000", "1,000,000"], correct: "10,000" },
  { kanji: "百円", kana: "ひゃくえん", answers: ["10 yen", "100 yen", "1,000 yen", "500 yen"], correct: "100 yen" },
  { kanji: "千円", kana: "せんえん", answers: ["100 yen", "1,000 yen", "10,000 yen", "2,000 yen"], correct: "1,000 yen" },
  { kanji: "一万円", kana: "いちまんえん", answers: ["1,000 yen", "10,000 yen", "100,000 yen", "1,000,000 yen"], correct: "10,000 yen" }, 
  { kanji: "行きます", kana: "いきます", answers: ["Pergi", "Datang", "Pulang", "Lari"], correct: "Pergi" },
  { kanji: "来ます", kana: "きます", answers: ["Datang", "Pergi", "Pulang", "Masuk"], correct: "Datang" },
  { kanji: "会います", kana: "あいます", answers: ["Bertemu", "Berbicara", "Berpisah", "Melihat"], correct: "Bertemu" },
  { kanji: "休みます", kana: "やすみます", answers: ["Libur, istirahat", "Bekerja", "Berlari", "Berenang"], correct: "Libur, istirahat" },
  { kanji: "日本", kana: "にほん", answers: ["Jepang", "China", "Korea", "Indonesia"], correct: "Jepang" },
  { kanji: "東京", kana: "とうきょう", answers: ["Tokyo", "Kyoto", "Osaka", "Nagoya"], correct: "Tokyo" },
  { kanji: "私", kana: "わたし", answers: ["Saya", "Kamu", "Dia", "Mereka"], correct: "Saya" },
  { kanji: "父", kana: "ちち", answers: ["Ayah", "Ibu", "Kakak", "Adik"], correct: "Ayah" },
  { kanji: "母", kana: "はは", answers: ["Ibu", "Ayah", "Paman", "Bibi"], correct: "Ibu" },
  { kanji: "子供", kana: "こども", answers: ["Anak", "Orang tua", "Bayi", "Murid"], correct: "Anak" },
  { kanji: "男", kana: "おとこ", answers: ["Laki-laki", "Perempuan", "Anak", "Orang"], correct: "Laki-laki" },
  { kanji: "女", kana: "おんな", answers: ["Perempuan", "Laki-laki", "Gadis", "Ibu"], correct: "Perempuan" },
  { kanji: "人", kana: "ひと", answers: ["Orang", "Hewan", "Benda", "Dunia"], correct: "Orang" },
  { kanji: "お父さん", kana: "おとうさん", answers: ["Ayah (orang lain)", "Ayah (sendiri)", "Paman", "Kakek"], correct: "Ayah (orang lain)" },
  { kanji: "お母さん", kana: "おかあさん", answers: ["Ibu (orang lain)", "Ibu (sendiri)", "Bibi", "Nenek"], correct: "Ibu (orang lain)" },
  { kanji: "何人", kana: "なんにん", answers: ["Berapa orang?", "Siapa?", "Dimana?", "Kapan?"], correct: "Berapa orang?" },
  { kanji: "国", kana: "くに", answers: ["Negara", "Kota", "Desa", "Wilayah"], correct: "Negara" },
  { kanji: "外国", kana: "がいこく", answers: ["Luar negri", "Dalam negri", "Kota asing", "Bahasa"], correct: "Luar negri" },
  { kanji: "~語", kana: "~ご", answers: ["Bahasa", "Kata", "Tulisan", "Negara"], correct: "Bahasa" },
  { kanji: "日本語", kana: "にほんご", answers: ["Bahasa jepang", "Bahasa inggris", "Bahasa china", "Bahasa indonesia"], correct: "Bahasa jepang" },
  { kanji: "英語", kana: "えいご", answers: ["Bahasa inggris", "Bahasa jepang", "Bahasa jerman", "Bahasa prancis"], correct: "Bahasa inggris" },
  { kanji: "中国語", kana: "ちゅうごくご", answers: ["Bahasa china", "Bahasa korea", "Bahasa jepang", "Bahasa thailand"], correct: "Bahasa china" },
  { kanji: "~人", kana: "~じん/~にん", answers: ["orang", "negara", "bahasa", "tahun"], correct: "orang" },
  { kanji: "日本人", kana: "にほんじん", answers: ["Orang jepang", "Orang asing", "Orang china", "Orang indonesia"], correct: "Orang jepang" },
  { kanji: "好き", kana: "すき", answers: ["Suka", "Benci", "Biasa", "Ingin"], correct: "Suka" },
  { kanji: "本", kana: "ほん", answers: ["Buku", "Pensil", "Kertas", "Meja"], correct: "Buku" },
  { kanji: "読書", kana: "どくしょ", answers: ["Bacaan", "Tulisan", "Laporan", "Buku"], correct: "Bacaan" },
  { kanji: "何", kana: "なに", answers: ["Apa?", "Siapa?", "Mana?", "Kapan?"], correct: "Apa?" },
  { kanji: "春", kana: "はる", answers: ["Musim semi", "Musim panas", "Musim gugur", "Musim dingin"], correct: "Musim semi" },
  { kanji: "夏", kana: "なつ", answers: ["Musim panas", "Musim semi", "Musim dingin", "Musim hujan"], correct: "Musim panas" },
  { kanji: "秋", kana: "あき", answers: ["Musim gugur", "Musim semi", "Musim panas", "Musim dingin"], correct: "Musim gugur" },
  { kanji: "冬", kana: "ふゆ", answers: ["Musim dingin", "Musim panas", "Musim gugur", "Musim semi"], correct: "Musim dingin" },
  { kanji: "今", kana: "いま", answers: ["Sekarang", "Besok", "Tadi", "Nanti"], correct: "Sekarang" },
  { kanji: "花", kana: "はな", answers: ["Bunga", "Daun", "Pohon", "Rumput"], correct: "Bunga" },
  { kanji: "海", kana: "うみ", answers: ["Laut", "Gunung", "Sungai", "Danau"], correct: "Laut" },
  { kanji: "山", kana: "やま", answers: ["Gunung", "Laut", "Hutan", "Lembah"], correct: "Gunung" },
  { kanji: "川", kana: "かわ", answers: ["Sungai", "Laut", "Sumur", "Kolam"], correct: "Sungai" },
  { kanji: "今日", kana: "きょう", answers: ["Hari ini", "Besok", "Kemarin", "Lusa"], correct: "Hari ini" },
  { kanji: "天気", kana: "てんき", answers: ["Cuaca", "Udara", "Suhu", "Angin"], correct: "Cuaca" },
  { kanji: "晴れ", kana: "はれ", answers: ["Cerah", "Hujan", "Berawan", "Salju"], correct: "Cerah" },
  { kanji: "雨", kana: "あめ", answers: ["Hujan", "Panas", "Berangin", "Mendung"], correct: "Hujan" },
  { kanji: "雪", kana: "ゆき", answers: ["Salju", "Hujan", "Es", "Kabut"], correct: "Salju" },
  { kanji: "雲", kana: "くも", answers: ["Mendung", "Cerah", "Hujan", "Berawan"], correct: "Mendung" },
  { kanji: "風", kana: "かぜ", answers: ["Angin", "Udara", "Awan", "Hujan"], correct: "Angin" },
  { kanji: "空", kana: "そら", answers: ["Langit", "Bumi", "Bintang", "Bulan"], correct: "Langit" },
  { kanji: "町", kana: "まち", answers: ["Kota", "Desa", "Jalan", "Negara"], correct: "Kota" },
  { kanji: "店", kana: "みせ", answers: ["Toko", "Rumah", "Sekolah", "Kantor"], correct: "Toko" },
  { kanji: "人気", kana: "にんき", answers: ["Popularitas, ketenaran", "Orang", "Udara", "Kekuatan"], correct: "Popularitas, ketenaran" },
  { kanji: "多い", kana: "おおい", answers: ["Banyak", "Sedikit", "Besar", "Kecil"], correct: "Banyak" },
  { kanji: "少ない", kana: "すくない", answers: ["Sedikit", "Banyak", "Jarang", "Sering"], correct: "Sedikit" },
  { kanji: "高い", kana: "たかい", answers: ["Mahal,Tinggi", "Murah", "Pendek", "Lama"], correct: "Mahal,Tinggi" },
  { kanji: "安い", kana: "やすい", answers: ["Murah", "Mahal", "Baru", "Bagus"], correct: "Murah" },
  { kanji: "広い", kana: "ひろい", answers: ["Luas", "Sempit", "Tinggi", "Besar"], correct: "Luas" },
  { kanji: "道", kana: "みち", answers: ["Jalan", "Arah", "Pintu", "Mobil"], correct: "Jalan" },
  { kanji: "通り", kana: "とおり", answers: ["Jalan", "Pintu", "Membeli", "Datang"], correct: "Jalan" },
  { kanji: "右", kana: "みぎ", answers: ["Kanan", "Kiri", "Atas", "Bawah"], correct: "Kanan" },
  { kanji: "左", kana: "ひだり", answers: ["Kiri", "Kanan", "Tengah", "Samping"], correct: "Kiri" },
  { kanji: "一つ", kana: "ひとつ", answers: ["Satu buah", "Dua buah", "Satu orang", "Satu kali"], correct: "Satu buah" },
  { kanji: "二つ", kana: "ふたつ", answers: ["Dua buah", "Satu buah", "Tiga buah", "Sepuluh buah"], correct: "Dua buah" },
  { kanji: "赤い", kana: "あかい", answers: ["Merah", "Biru", "Hitam", "Putih"], correct: "Merah" },
  { kanji: "青い", kana: "あおい", answers: ["Biru", "Merah", "Hijau", "Kuning"], correct: "Biru" },
  { kanji: "黒い", kana: "くろい", answers: ["Hitam", "Putih", "Abu-abu", "Cokelat"], correct: "Hitam" },
  { kanji: "白い", kana: "しろい", answers: ["Putih", "Hitam", "Bening", "Merah"], correct: "Putih" },
  { kanji: "時間", kana: "じかん", answers: ["Waktu", "Jam", "Menit", "Detik"], correct: "Waktu" },
  { kanji: "場所", kana: "ばしょ", answers: ["Tempat", "Arah", "Kota", "Negara"], correct: "Tempat" },
  { kanji: "駅", kana: "えき", answers: ["Stasiun", "Bandara", "Pelabuhan", "Terminal"], correct: "Stasiun" },
  { kanji: "日", kana: "ひ", answers: ["Matahari", "Bulan", "Api", "Tanah"], correct: "Matahari" },
  { kanji: "出かけます", kana: "でかけます", answers: ["Meninggalkan rumah", "Masuk rumah", "Pergi sekolah", "Bekerja"], correct: "Meninggalkan rumah" },
  { kanji: "待ちます", kana: "まちます", answers: ["Menunggu", "Membawa", "Membeli", "Meminta"], correct: "Menunggu" },
  { kanji: "止まります", kana: "とまります", answers: ["Berhenti", "Berjalan", "Berenang", "Berlari"], correct: "Berhenti" },
  { kanji: "食事", kana: "しょくじ", answers: ["Makan bersama", "Pekerjaan", "Belanja", "Berjalan"], correct: "Makan bersama" },
  { kanji: "仕事", kana: "しごと", answers: ["Pekerjaan", "Pelajaran", "Hobi", "Wisata"], correct: "Pekerjaan" },
  { kanji: "前", kana: "まえ", answers: ["Sebelum", "Setelah", "Samping", "Dalam"], correct: "Sebelum" },
  { kanji: "後", kana: "あと", answers: ["Setelah", "Sebelum", "Luar", "Belakang"], correct: "Setelah" },
  { kanji: "朝", kana: "あさ", answers: ["Pagi", "Siang", "Malam", "Sore"], correct: "Pagi" },
  { kanji: "昼", kana: "ひる", answers: ["Siang", "Pagi", "Sore", "Malam"], correct: "Siang" },
  { kanji: "夜", kana: "よる", answers: ["Malam", "Siang", "Pagi", "Subuh"], correct: "Malam" },
  { kanji: "乗ります", kana: "のります", answers: ["Naik", "Turun", "Masuk", "Keluar"], correct: "Naik" },
  { kanji: "学校", kana: "がっこう", answers: ["Sekolahan", "Rumah sakit", "Kantor", "Pasar"], correct: "Sekolahan" },
  { kanji: "小学校", kana: "しょうがっこう", answers: ["SD", "SMP", "SMA", "Universitas"], correct: "SD" },
  { kanji: "中学校", kana: "ちゅうがっこう", answers: ["SMP", "SD", "SMA", "TK"], correct: "SMP" },
  { kanji: "高校", kana: "こうこう", answers: ["SMA", "SMP", "Universitas", "Kursus"], correct: "SMA" },
  { kanji: "大学", kana: "だいがく", answers: ["Universitas", "Sekolah", "Perpustakaan", "Laboratorium"], correct: "Universitas" },
  { kanji: "先生", kana: "せんせい", answers: ["Guru", "Murid", "Dokter", "Polisi"], correct: "Guru" },
  { kanji: "学生", kana: "がくせい", answers: ["Murid, siswa", "Guru", "Orang tua", "Pegawai"], correct: "Murid, siswa" },
  { kanji: "~年生", kana: "~ねんせい", answers: ["Kelas ~", "Tahun ~", "Orang ~", "Bahasa ~"], correct: "Kelas ~" },
  { kanji: "勉強", kana: "べんきょう", answers: ["Belajar", "Permainan", "Pekerjaan", "Olahraga"], correct: "Belajar" },
  { kanji: "文化", kana: "ぶんか", answers: ["Budaya", "Sejarah", "Teknologi", "Seni"], correct: "Budaya" },
  { kanji: "音楽", kana: "おんがく", answers: ["Musik", "Gambar", "Lagu", "Film"], correct: "Musik" },
  { kanji: "旅行", kana: "りょこう", answers: ["Wisata", "Bisnis", "Pelajaran", "Olahraga"], correct: "Wisata" },
  { kanji: "留学", kana: "りゅうがく", answers: ["Belajar di luar negri", "Bekerja di luar negri", "Pindah rumah", "Wisata"], correct: "Belajar di luar negri" },
  { kanji: "友達", kana: "ともだち", answers: ["Teman", "Musuh", "Saudara", "Pacar"], correct: "Teman" },
  { kanji: "楽しい", kana: "たのしい", answers: ["Gembira", "Sedih", "Marah", "Takut"], correct: "Gembira" },
  { kanji: "週", kana: "しゅう", answers: ["Minggu", "Bulan", "Tahun", "Hari"], correct: "Minggu" },
  { kanji: "一回", kana: "~かい", answers: ["~kali", "buah", "orang", "lembar"], correct: "~kali" },
  { kanji: "食べ物", kana: "たべもの", answers: ["Makanan", "Minuman", "Pakaian", "Alat"], correct: "Makanan" },
  { kanji: "飲物", kana: "のみもの", answers: ["Minuman", "Makanan", "Sayuran", "Buah"], correct: "Minuman" },
  { kanji: "お茶", kana: "おちゃ", answers: ["Teh hijau", "Kopi", "Susu", "Air putih"], correct: "Teh hijau" },
  { kanji: "お酒", kana: "おさけ", answers: ["Sake", "Teh", "Soda", "Jus"], correct: "Sake" },
  { kanji: "作ります", kana: "つくります", answers: ["Membuat", "Membeli", "Memakan", "Membuang"], correct: "Membuat" },
  { kanji: "持っていきます", kana: "もっていきます", answers: ["Membawa pergi", "Membawa datang", "Membawa pulang", "Meninggalkan"], correct: "Membawa pergi" },
  { kanji: "お願いします", kana: "おねがいします", answers: ["Tolong", "Terima kasih", "Maaf", "Permisi"], correct: "Tolong" },
  { kanji: "料理", kana: "りょうり", answers: ["Masakan", "Minuman", "Bahan", "Rasa"], correct: "Masakan" },
  { kanji: "味", kana: "あじ", answers: ["Rasa", "Warna", "Bau", "Bentuk"], correct: "Rasa" },
  { kanji: "色", kana: "いろ", answers: ["Warna", "Rasa", "Jenis", "Harga"], correct: "Warna" },
  { kanji: "野菜", kana: "やさい", answers: ["Sayuran", "Daging", "Ikan", "Buah"], correct: "Sayuran" },
  { kanji: "少し", kana: "すこし", answers: ["Sedikit", "Banyak", "Cukup", "Sangat"], correct: "Sedikit" },
  { kanji: "中", kana: "なか", answers: ["Dalam", "Luar", "Atas", "Bawah"], correct: "Dalam" },
  { kanji: "入っています", kana: "はいっています", answers: ["Masuk", "Keluar", "Hilang", "Penuh"], correct: "Masuk" },
  { kanji: "会社", kana: "かいしゃ", answers: ["Perusahaan", "Sekolah", "Rumah sakit", "Pasar"], correct: "Perusahaan" },
  { kanji: "本社", kana: "ほんしゃ", answers: ["Kantor pusat", "Kantor cabang", "Kantor lama", "Kantor baru"], correct: "Kantor pusat" },
  { kanji: "支社", kana: "ししゃ", answers: ["Kantor cabang", "Kantor pusat", "Kantor asing", "Kantor wilayah"], correct: "Kantor cabang" },
  { kanji: "出張", kana: "しゅっちょう", answers: ["Dinas luar kota", "Liburan", "Pindah kantor", "Rapat"], correct: "Dinas luar kota" },
  { kanji: "空港", kana: "くうこう", answers: ["Bandara", "Stasiun", "Pelabuhan", "Terminal"], correct: "Bandara" },
  { kanji: "出発", kana: "しゅっぱつ", answers: ["Keberangkatan", "Kedatangan", "Perjalanan", "Transit"], correct: "Keberangkatan" },
  { kanji: "到着", kana: "とうちゃく", answers: ["Kedatangan", "Keberangkatan", "Keterlambatan", "Kepulangan"], correct: "Kedatangan" },
  { kanji: "午前", kana: "ごぜん", answers: ["AM", "PM", "Pagi", "Malam"], correct: "AM" },
  { kanji: "午後", kana: "ごご", answers: ["PM", "AM", "Siang", "Sore"], correct: "PM" },
  { kanji: "自分", kana: "じぶん", answers: ["Sendiri", "Orang lain", "Mereka", "Kita"], correct: "Sendiri" },
  { kanji: "電話", kana: "でんわ", answers: ["Telepon", "Surat", "Internet", "Pesan"], correct: "Telepon" },
  { kanji: "電気", kana: "でんき", answers: ["Listrik", "Udara", "Air", "Baterai"], correct: "Listrik" },
  { kanji: "電車", kana: "でんしゃ", answers: ["Kereta", "Mobil", "Bus", "Sepeda"], correct: "Kereta" },
  { kanji: "車", kana: "くるま", answers: ["Mobil", "Motor", "Sepeda", "Becak"], correct: "Mobil" },
  { kanji: "送ります", kana: "おくります", answers: ["Mengirim", "Menerima", "Membawa", "Melihat"], correct: "Mengirim" },
  { kanji: "使います", kana: "つかいます", answers: ["Menggunakan", "Membuat", "Membeli", "Menjual"], correct: "Menggunakan" },
  { kanji: "借ります", kana: "かります", answers: ["Meminjam", "Meminjamkan", "Membeli", "Menjual"], correct: "Meminjam" },
  { kanji: "体", kana: "からだ", answers: ["Badan", "Kepala", "Kaki", "Tangan"], correct: "Badan" },
  { kanji: "頭", kana: "あたま", answers: ["Kepala", "Mata", "Mulut", "Hidung"], correct: "Kepala" },
  { kanji: "目", kana: "め", answers: ["Mata", "Telinga", "Tangan", "Kaki"], correct: "Mata" },
  { kanji: "口", kana: "くち", answers: ["Mulut", "Hidung", "Mata", "Pipi"], correct: "Mulut" },
  { kanji: "耳", kana: "みみ", answers: ["Telinga", "Mata", "Kepala", "Rambut"], correct: "Telinga" },
  { kanji: "手", kana: "て", answers: ["Tangan", "Kaki", "Badan", "Jari"], correct: "Tangan" },
  { kanji: "足", kana: "あし", answers: ["Kaki", "Tangan", "Badan", "Kepala"], correct: "Kaki" },
  { kanji: "上", kana: "うえ", answers: ["Atas", "Bawah", "Samping", "Dalam"], correct: "Atas" },
  { kanji: "下", kana: "した", answers: ["Bawah", "Atas", "Luar", "Belakang"], correct: "Bawah" },
  { kanji: "毎~", kana: "まい~", answers: ["setiap", "selalu", "sering", "kadang"], correct: "setiap" },
  { kanji: "毎朝", kana: "まいあさ", answers: ["setiap pagi", "setiap siang", "setiap malam", "setiap hari"], correct: "setiap pagi" },
  { kanji: "毎日", kana: "まいにち", answers: ["Setiap hari", "Setiap minggu", "Setiap bulan", "Setiap tahun"], correct: "Setiap hari" },
  { kanji: "週末", kana: "しゅうまつ", answers: ["Akhir pekan", "Awal pekan", "Hari kerja", "Hari libur"], correct: "Akhir pekan" },
  { kanji: "元気", kana: "げんき", answers: ["Sehat", "Sakit", "Lelah", "Semangat"], correct: "Sehat" },
  { kanji: "外", kana: "そと", answers: ["Luar", "Dalam", "Atas", "Bawah"], correct: "Luar" },
  { kanji: "起きます", kana: "おきます", answers: ["Bangun tidur", "Tidur", "Mandi", "Makan"], correct: "Bangun tidur" },
  { kanji: "歩きます", kana: "あるきます", answers: ["Berjalan", "Berlari", "Berenang", "Melompat"], correct: "Berjalan" },
  { kanji: "走ります", kana: "はしります", answers: ["Berlari", "Berjalan", "Terbang", "Duduk"], correct: "Berlari" },
  { kanji: "泳ぎます", kana: "およぎます", answers: ["Berenang", "Menyelam", "Berlayar", "Mandi"], correct: "Berenang" },
  { kanji: "お祝い", kana: "おいわい", answers: ["Perayaan", "Pesta", "Kado", "Doa"], correct: "Perayaan" },
  { kanji: "誕生日", kana: "たんじょうび", answers: ["Ulang tahun", "Hari lahir", "Hari kematian", "Hari pernikahan"], correct: "Ulang tahun" },
  { kanji: "結婚", kana: "けっこん", answers: ["Pernikahan", "Perceraian", "Pertunangan", "Pacaran"], correct: "Pernikahan" },
  { kanji: "絵", kana: "え", answers: ["Gambar, lukisan", "Foto", "Patung", "Musik"], correct: "Gambar, lukisan" },
  { kanji: "写真", kana: "しゃしん", answers: ["Foto", "Gambar", "Film", "Kamera"], correct: "Foto" },
  { kanji: "時計", kana: "とけい", answers: ["Jam", "Waktu", "Kalender", "Kaca"], correct: "Jam" },
  { kanji: "着ます", kana: "きます", answers: ["Memakai pakaian", "Membeli pakaian", "Mencuci pakaian", "Membuang pakaian"], correct: "Memakai pakaian" },
  { kanji: "先~", kana: "せん~", answers: ["~lalu", "~depan", "~sekarang", "~besok"], correct: "~lalu" },
  { kanji: "先週", kana: "せんしゅう", answers: ["Minggu lalu", "Minggu ini", "Minggu depan", "Dua minggu lalu"], correct: "Minggu lalu" },
  { kanji: "今月", kana: "こんげつ", answers: ["Bulan ini", "Bulan lalu", "Bulan depan", "Setiap bulan"], correct: "Bulan ini" },
  { kanji: "来年", kana: "らいねん", answers: ["Tahun depan", "Tahun lalu", "Tahun ini", "Setiap tahun"], correct: "Tahun depan" },
  { kanji: "今年", kana: "ことし", answers: ["Tahun ini", "Tahun depan", "Tahun lalu", "Tahun baru"], correct: "Tahun ini" },
  { kanji: "去年", kana: "きょねん", answers: ["Tahun lalu", "Tahun ini", "Tahun depan", "Dua tahun lalu"], correct: "Tahun lalu" },
  { kanji: "家", kana: "いえ", answers: ["Rumah", "Apartemen", "Gedung", "Kantor"], correct: "Rumah" },
  { kanji: "思います", kana: "おもいます", answers: ["Mengira", "Melihat", "Mendengar", "Berkata"], correct: "Mengira" },
  { kanji: "自己紹介", kana: "じこしょうかい", answers: ["Perkenalan", "Pidato", "Cerita", "Pelajaran"], correct: "Perkenalan" },
  { kanji: "名前", kana: "なまえ", answers: ["Nama", "Alamat", "Umur", "Pekerjaan"], correct: "Nama" },
  { kanji: "意味", kana: "いみ", answers: ["Arti", "Kata", "Bunyi", "Tanda"], correct: "Arti" },
  { kanji: "本屋", kana: "ほんや", answers: ["Toko buku", "Toko roti", "Toko sepatu", "Toko baju"], correct: "Toko buku" },
  { kanji: "近く", kana: "ちかく", answers: ["Dekat", "Jauh", "Samping", "Depan"], correct: "Dekat" },
  { kanji: "住みます", kana: "すみます", answers: ["Tinggal", "Bekerja", "Belajar", "Pergi"], correct: "Tinggal" },
  { kanji: "働きます", kana: "はたらきます", answers: ["Bekerja", "Bermain", "Beristirahat", "Berhenti"], correct: "Bekerja" },
  { kanji: "~番目", kana: "~ばんめ", answers: ["Urutan yang", "Nomor", "Bagian", "Jenis"], correct: "Urutan yang" },
  { kanji: "兄", kana: "あに", answers: ["Kakak laki (sendiri)", "Adik laki", "Kakak perempuan", "Adik perempuan"], correct: "Kakak laki (sendiri)" },
  { kanji: "お兄さん", kana: "おにいさん", answers: ["Kakak laki (orang lain)", "Adik laki", "Paman", "Kakek"], correct: "Kakak laki (orang lain)" },
  { kanji: "姉", kana: "あね", answers: ["Kakak perempuan (sendiri)", "Adik perempuan", "Kakak laki", "Ibu"], correct: "Kakak perempuan (sendiri)" },
  { kanji: "お姉さん", kana: "おねえさん", answers: ["Kakak perempuan (orang lain)", "Bibi", "Nenek", "Ibu"], correct: "Kakak perempuan (orang lain)" },
  { kanji: "弟", kana: "おとうと", answers: ["Adik laki (sendiri)", "Kakak laki", "Adik perempuan", "Anak"], correct: "Adik laki (sendiri)" },
  { kanji: "妹", kana: "いもうと", answers: ["Adik perempuan (sendiri)", "Kakak perempuan", "Adik laki", "Istri"], correct: "Adik perempuan (sendiri)" },
  { kanji: "家族", kana: "かぞく", answers: ["Keluarga", "Teman", "Tetangga", "Masyarakat"], correct: "Keluarga" },
  { kanji: "長い", kana: "ながい", answers: ["Panjang", "Pendek", "Lama", "Baru"], correct: "Panjang" },
  { kanji: "短い", kana: "みじかい", answers: ["Pendek", "Panjang", "Kecil", "Sempit"], correct: "Pendek" },
  { kanji: "低い", kana: "ひくい", answers: ["Rendah", "Tinggi", "Mahal", "Murah"], correct: "Rendah" },
  { kanji: "上手", kana: "じょうず", answers: ["Pandai", "Bodoh", "Tangan", "Atas"], correct: "Pandai" },
  { kanji: "歌", kana: "うた", answers: ["Lagu", "Musik", "Suara", "Nada"], correct: "Lagu" },
  { kanji: "歌います", kana: "うたいます", answers: ["Menyanyi", "Mendengar", "Menari", "Berteriak"], correct: "Menyanyi" },
  { kanji: "客", kana: "きゃく", answers: ["Tamu", "Pemilik", "Pelayan", "Pedagang"], correct: "Tamu" },
  { kanji: "注文", kana: "ちゅうもん", answers: ["Pesanan", "Laporan", "Tugas", "Janji"], correct: "Pesanan" },
  { kanji: "洋食", kana: "ようしょく", answers: ["Makanan barat", "Makanan jepang", "Makanan cina", "Makanan laut"], correct: "Makanan barat" },
  { kanji: "和食", kana: "わしょく", answers: ["Makanan jepang", "Makanan barat", "Makanan sehat", "Makanan ringan"], correct: "Makanan jepang" },
  { kanji: "牛肉", kana: "ぎゅうにく", answers: ["Daging sapi", "Daging babi", "Daging ayam", "Daging ikan"], correct: "Daging sapi" },
  { kanji: "地方", kana: "ちほう", answers: ["Daerah, wilayah", "Pusat", "Kota", "Negara"], correct: "Daerah, wilayah" },
  { kanji: "有名", kana: "ゆうめい", answers: ["Terkenal", "Nama", "Kaya", "Pintar"], correct: "Terkenal" },
  { kanji: "生", kana: "なま", answers: ["Mentah", "Matang", "Segar", "Hidup"], correct: "Mentah" },
  { kanji: "冷たい", kana: "つめたい", answers: ["Dingin (benda)", "Panas", "Hangat", "Sejuk"], correct: "Dingin (benda)" },
  { kanji: "ご飯", kana: "ごはん", answers: ["Nasi", "Lauk", "Sayur", "Buah"], correct: "Nasi" },
  { kanji: "塩", kana: "しお", answers: ["Garam", "Gula", "Merica", "Cuka"], correct: "Garam" },
  { kanji: "全部", kana: "ぜんぶ", answers: ["Semua", "Sebagian", "Sedikit", "Satu"], correct: "Semua" },
  { kanji: "~方", kana: "~かた", answers: ["Cara-", "Arah", "Orang", "Tempat"], correct: "Cara-" },
  { kanji: "食べ方", kana: "たべかた", answers: ["Cara makan", "Cara masak", "Cara beli", "Cara potong"], correct: "Cara makan" },
  { kanji: "熱い", kana: "あつい", answers: ["Panas", "Dingin", "Pedas", "Pahit"], correct: "Panas" },
  { kanji: "苦手", kana: "にがて", answers: ["Susah, berat, tidak begitu suka", "Pandai", "Suka", "Mudah"], correct: "Susah, berat, tidak begitu suka" },
  { kanji: "入れます", kana: "いれます", answers: ["Memasukkan", "Mengeluarkan", "Membuang", "Membeli"], correct: "Memasukkan" },
  { kanji: "木", kana: "き", answers: ["Pohon", "Kayu", "Hutan", "Bunga"], correct: "Pohon" },
  { kanji: "森", kana: "もり", answers: ["Hutan", "Pohon", "Gunung", "Laut"], correct: "Hutan" },
  { kanji: "島", kana: "しま", answers: ["Pulau", "Negara", "Kota", "Benua"], correct: "Pulau" },
  { kanji: "自然", kana: "しぜん", answers: ["Alam", "Budaya", "Sejarah", "Dunia"], correct: "Alam" },
  { kanji: "船", kana: "ふね", answers: ["Kapal", "Pesawat", "Mobil", "Kereta"], correct: "Kapal" },
  { kanji: "暑い", kana: "あつい", answers: ["Panas", "Dingin", "Cerah", "Mendung"], correct: "Panas" },
  { kanji: "帰ります", kana: "かえります", answers: ["Pulang", "Pergi", "Datang", "Masuk"], correct: "Pulang" },
  { kanji: "予約します", kana: "よやくします", answers: ["Memesan", "Membeli", "Menjual", "Membayar"], correct: "Memesan" },
  { kanji: "運転します", kana: "うんてんします", answers: ["Menyetir", "Berjalan", "Bekerja", "Berhenti"], correct: "Menyetir" },
  { kanji: "~中", kana: "~ちゅう /~じゅう", answers: ["Sedang/dalam ~", "Setelah ~", "Sebelum ~", "Luar ~"], correct: "Sedang/dalam ~" },
  { kanji: "旅行中", kana: "りょこうちゅう", answers: ["Sedang wisata", "Setelah wisata", "Sebelum wisata", "Hobi wisata"], correct: "Sedang wisata" },
  { kanji: "観光地", kana: "かんこうち", answers: ["Tempat wisata", "Kantor wisata", "Peta wisata", "Bus wisata"], correct: "Tempat wisata" },
  { kanji: "女性", kana: "じょせい", answers: ["Wanita", "Pria", "Ibu", "Gadis"], correct: "Wanita" },
  { kanji: "男性", kana: "だんせい", answers: ["Pria", "Wanita", "Ayah", "Pemuda"], correct: "Pria" },
  { kanji: "動物", kana: "どうぶつ", answers: ["Hewan", "Benda", "Tanaman", "Manusia"], correct: "Hewan" },
  { kanji: "空気", kana: "くうき", answers: ["Udara", "Listrik", "Air", "Api"], correct: "Udara" },
  { kanji: "料金", kana: "りょうきん", answers: ["Biaya / tarif", "Uang", "Gaji", "Pajak"], correct: "Biaya / tarif" },
  { kanji: "無料", kana: "むりょう", answers: ["Gratis", "Mahal", "Murah", "Diskon"], correct: "Gratis" },
  { kanji: "明るい", kana: "あかるい", answers: ["Terang", "Gelap", "Bersih", "Kotor"], correct: "Terang" },
  { kanji: "便利", kana: "べんり", answers: ["Praktis", "Sulit", "Lama", "Cepat"], correct: "Praktis" },
  { kanji: "一年中", kana: "いちねんじゅう", answers: ["Dalam satu tahun", "Setiap tahun", "Tahun depan", "Tahun lalu"], correct: "Dalam satu tahun" },
  { kanji: "受付", kana: "うけつけ", answers: ["Penerima tamu", "Kasir", "Manajer", "Pelayan"], correct: "Penerima tamu" },
  { kanji: "広場", kana: "ひろば", answers: ["Lapangan", "Gedung", "Pasar", "Rumah"], correct: "Lapangan" },
  { kanji: "問題", kana: "もんだい", answers: ["Soal, masalah", "Jawaban", "Cerita", "Tugas"], correct: "Soal, masalah" },
  { kanji: "同じ", kana: "おなじ", answers: ["Sama", "Beda", "Mirip", "Lain"], correct: "Sama" },
  { kanji: "集まります", kana: "あつまります", answers: ["Berkumpul", "Berpisah", "Berhenti", "Berjalan"], correct: "Berkumpul" },
  { kanji: "始まります", kana: "はじまります", answers: ["Mulai", "Selesai", "Berhenti", "Batal"], correct: "Mulai" },
  { kanji: "終わります", kana: "おわります", answers: ["Selesai", "Mulai", "Lanjut", "Istirahat"], correct: "Selesai" },
  { kanji: "中止します", kana: "ちゅうしします", answers: ["Mengurungkan, membatalkan", "Melanjutkan", "Memulai", "Menunda"], correct: "Mengurungkan, membatalkan" },
  { kanji: "教えます", kana: "おしえます", answers: ["Memberitahu", "Belajar", "Melihat", "Mencari"], correct: "Memberitahu" },
  { kanji: "祭り", kana: "まつり", answers: ["Perayaan", "Upacara", "Pesta", "Hiburan"], correct: "Perayaan" },
  { kanji: "日本祭り", kana: "にほんまつり", answers: ["Perayaan jepang", "Wisata jepang", "Budaya jepang", "Sejarah jepang"], correct: "Perayaan jepang" },
  { kanji: "会場", kana: "かいじょう", answers: ["Ruang pertemuan", "Lapangan", "Pasar", "Stasiun"], correct: "Ruang pertemuan" },
  { kanji: "入場料", kana: "にゅうじょうりょう", answers: ["Tarif masuk", "Tarif parkir", "Harga barang", "Gaji"], correct: "Tarif masuk" },
  { kanji: "参加者", kana: "さんかしゃ", answers: ["Peserta", "Penonton", "Penyelenggara", "Tamu"], correct: "Peserta" },
  { kanji: "急ぎます", kana: "いそぎます", answers: ["Buru-buru", "Pelan-pelan", "Berhenti", "Beristirahat"], correct: "Buru-buru" },
  { kanji: "決めます", kana: "きめます", answers: ["Menentukan", "Memilih", "Membeli", "Menjual"], correct: "Menentukan" },
  { kanji: "知ります", kana: "しります", answers: ["Kenal, tahu", "Lupa", "Cari", "Tanya"], correct: "Kenal, tahu" },
  { kanji: "正月", kana: "しょうがつ", answers: ["Tahun baru", "Bulan depan", "Akhir tahun", "Hari libur"], correct: "Tahun baru" },
  { kanji: "年末", kana: "ねんまつ", answers: ["Akhir tahun", "Awal tahun", "Setiap tahun", "Bulan lalu"], correct: "Akhir tahun" },
  { kanji: "年始", kana: "ねんし", answers: ["Awal tahun", "Akhir tahun", "Tahun depan", "Libur tahun"], correct: "Awal tahun" },
  { kanji: "親", kana: "おや", answers: ["Orang tua", "Anak", "Saudara", "Teman"], correct: "Orang tua" },
  { kanji: "忙しい", kana: "いそがしい", answers: ["Sibuk", "Senggang", "Lelah", "Malas"], correct: "Sibuk" },
  { kanji: "特別", kana: "とくべつ", answers: ["Istimewa, special", "Biasa", "Umum", "Langka"], correct: "Istimewa, special" },
  { kanji: "帰国", kana: "きこく", answers: ["Pulang ke negara", "Pergi ke luar negri", "Pindah rumah", "Wisata"], correct: "Pulang ke negara" },
  { kanji: "喜びます", kana: "よろこびます", answers: ["Merasa senang/gembira", "Merasa sedih", "Merasa marah", "Merasa takut"], correct: "Merasa senang/gembira" },
  { kanji: "幸せ", kana: "しあわせ", answers: ["Bahagia", "Kaya", "Pintar", "Sehat"], correct: "Bahagia" },
  { kanji: "成長", kana: "せいちょう", answers: ["Pertumbuhan, perkembangan", "Kematian", "Kehancuran", "Pengurangan"], correct: "Pertumbuhan, perkembangan" },
  { kanji: "長生き", kana: "ながいき", answers: ["Umur panjang, hidup lama", "Mati muda", "Sakit parah", "Sehat selalu"], correct: "Umur panjang, hidup lama" },
  { kanji: "願い事", kana: "ねがいこと", answers: ["Keinginan, kemauan, harapan", "Kenyataan", "Kenangan", "Kewajiban"], correct: "Keinginan, kemauan, harapan" },
  { kanji: "合格", kana: "ごうかく", answers: ["Lulus", "Gagal", "Mencoba", "Mendaftar"], correct: "Lulus" },
  { kanji: "試験", kana: "しけん", answers: ["Ujian", "Latihan", "Tugas", "Pelajaran"], correct: "Ujian" },
  { kanji: "大人", kana: "おとな", answers: ["Orang Dewasa", "Anak kecil", "Bayi", "Orang tua"], correct: "Orang Dewasa" },
  { kanji: "~式(成人式)", kana: "~しき(せいじんしき)", answers: ["Upacara (upacara kedewasaan)", "Pesta", "Rapat", "Latihan"], correct: "Upacara (upacara kedewasaan)" },
  { kanji: "~市(さいたま市)", kana: "~し(さいたまし)", answers: ["Kota (kota saitama)", "Desa", "Negara", "Provinsi"], correct: "Kota (kota saitama)" },
  { kanji: "商品", kana: "しょうひん", answers: ["Barang dagangan", "Hadiah", "Bahan", "Alat"], correct: "Barang dagangan" },
  { kanji: "電気製品", kana: "でんきせいひん", answers: ["Peralatan listrik", "Alat dapur", "Kendaraan", "Pakaian"], correct: "Peralatan listrik" },
  { kanji: "電子レンジ", kana: "でんしレンジ", answers: ["Oven", "Kulkas", "Mesin cuci", "Kompor"], correct: "Oven" },
  { kanji: "~機(そうじ機)", kana: "~き(そうじき)", answers: ["Mesin~(mesin penghisap debu)", "Alat", "Wadah", "Tempat"], correct: "Mesin~(mesin penghisap debu)" },
  { kanji: "店員", kana: "てんいん", answers: ["Penjaga toko", "Pemilik toko", "Pembeli", "Pencuri"], correct: "Penjaga toko" },
  { kanji: "調子", kana: "ちょうし", answers: ["Keadaan, kondisi", "Rasa", "Warna", "Bunyi"], correct: "Keadaan, kondisi" },
  { kanji: "悪い", kana: "わるい", answers: ["Jelek", "Bagus", "Indah", "Mahal"], correct: "Jelek" },
  { kanji: "動きます", kana: "うごきます", answers: ["Bergerak", "Berhenti", "Tidur", "Makan"], correct: "Bergerak" },
  { kanji: "考えます", kana: "かんがえます", answers: ["Berfikir", "Melihat", "Mendengar", "Berkata"], correct: "Berfikir" },
  { kanji: "音", kana: "おと", answers: ["Suara", "Cahaya", "Rasa", "Warna"], correct: "Suara" },
  { kanji: "出ます", kana: "でます", answers: ["Keluar", "Masuk", "Naik", "Turun"], correct: "Keluar" },
  { kanji: "機能", kana: "きのう", answers: ["Fungsi", "Harga", "Bentuk", "Ukuran"], correct: "Fungsi" },
  { kanji: "省エネ", kana: "しょうエネ", answers: ["Penghematan energy", "Pemborosan", "Penggunaan", "Produksi"], correct: "Penghematan energy" },
  { kanji: "日本製", kana: "にほんせい", answers: ["Produk/buatan jepang", "Produk impor", "Produk mahal", "Produk lama"], correct: "Produk/buatan jepang" },
  { kanji: "重い", kana: "おもい", answers: ["Berat", "Ringan", "Besar", "Kecil"], correct: "Berat" },
  { kanji: "軽い", kana: "かるい", answers: ["Ringan", "Berat", "Murah", "Mudah"], correct: "Ringan" },
  { kanji: "静か", kana: "しずか", answers: ["Tenang", "Ramai", "Bising", "Keras"], correct: "Tenang" },
  { kanji: "早く", kana: "はやく", answers: ["Cepat", "Lambat", "Lama", "Baru"], correct: "Cepat" },
  { kanji: "方(こっちの方)", kana: "ほう(こっちのほう)", answers: ["Arah(arah disini)", "Tempat", "Orang", "Waktu"], correct: "Arah(arah disini)" },
  { kanji: "洗います", kana: "あらいます", answers: ["Mencuci", "Membuang", "Membeli", "Memakai"], correct: "Mencuci" },
  { kanji: "満足します", kana: "まんぞくします", answers: ["Puas, merasa puas", "Kecewa", "Marah", "Sedih"], correct: "Puas, merasa puas" },
  { kanji: "京都", kana: "きょうと", answers: ["Kyoto", "Tokyo", "Osaka", "Nara"], correct: "Kyoto" },
  { kanji: "神社", kana: "じんじゃ", answers: ["Kuil sinto", "Kuil budha", "Gereja", "Masjid"], correct: "Kuil sinto" },
  { kanji: "お寺", kana: "おてら", answers: ["Kuil", "Pasar", "Sekolah", "Rumah"], correct: "Kuil" },
  { kanji: "仏教", kana: "ぶっきょう", answers: ["Agama budha", "Agama sinto", "Agama kristen", "Agama islam"], correct: "Agama budha" },
  { kanji: "歴史", kana: "れきし", answers: ["Sejarah", "Budaya", "Teknologi", "Masa depan"], correct: "Sejarah" },
  { kanji: "世界", kana: "せかい", answers: ["Dunia", "Negara", "Kota", "Langit"], correct: "Dunia" },
  { kanji: "中心", kana: "ちゅうしん", answers: ["Pusat", "Pinggir", "Atas", "Bawah"], correct: "Pusat" },
  { kanji: "世紀", kana: "せいき", answers: ["Abad-", "Tahun-", "Bulan-", "Hari-"], correct: "Abad-" },
  { kanji: "~的", kana: "~てき", answers: ["Berbau~/ke~ an", "Seperti", "Karena", "Untuk"], correct: "Berbau~/ke~ an" },
  { kanji: "日本的", kana: "にほんてき", answers: ["Berbau jepang", "Orang jepang", "Bahasa jepang", "Barang jepang"], correct: "Berbau jepang" },
  { kanji: "歴史的", kana: "れきしてき", answers: ["Bersejarah", "Budaya", "Kuno", "Modern"], correct: "Bersejarah" },
  { kanji: "飲食", kana: "いんしょく", answers: ["Makan minum", "Makan saja", "Minum saja", "Bekerja"], correct: "Makan minum" },
  { kanji: "禁止", kana: "きんし", answers: ["Larangan", "Perintah", "Anjuran", "Hobi"], correct: "Larangan" },
  { kanji: "說明", kana: "せつめい", answers: ["Penjelasan", "Laporan", "Cerita", "Tugas"], correct: "Penjelasan" },
  { kanji: "道具", kana: "どうぐ", answers: ["Peralatan", "Bahan", "Barang", "Mesin"], correct: "Peralatan" },
  { kanji: "博物馆", kana: "はくぶつかん", answers: ["Museum", "Perpustakaan", "Sekolah", "Taman"], correct: "Museum" },
  { kanji: "必要", kana: "ひつよう", answers: ["Keperluan, kebutuhan", "Keinginan", "Hobi", "Tugas"], correct: "Keperluan, kebutuhan" },
  { kanji: "~階(階)", kana: "~かい(にかい)", answers: ["Lantai (lantai 2)", "Kamar", "Gedung", "Rumah"], correct: "Lantai (lantai 2)" },
  { kanji: "油", kana: "あぶら", answers: ["Minyak, oli", "Air", "Susu", "Cuka"], correct: "Minyak, oli" },
  { kanji: "紙", kana: "かみ", answers: ["Kertas", "Plastik", "Kain", "Kayu"], correct: "Kertas" },
  { kanji: "温度", kana: "おんど", answers: ["Suhu, derajat", "Waktu", "Panjang", "Berat"], correct: "Suhu, derajat" },
  { kanji: "活動", kana: "かつどう", answers: ["Kegiatan, aktivitas", "Istirahat", "Tidur", "Makan"], correct: "Kegiatan, aktivitas" },
  { kanji: "会議室", kana: "かいぎしつ", answers: ["Ruang rapat", "Ruang kelas", "Ruang makan", "Ruang tamu"], correct: "Ruang rapat" },
  { kanji: "寒い", kana: "さむい", answers: ["Dingin (suhu)", "Panas", "Sejuk", "Hangat"], correct: "Dingin (suhu)" },
  { kanji: "出します", kana: "だします", answers: ["Mengeluarkan, mengirim (surat)", "Memasukkan", "Menerima", "Membeli"], correct: "Mengeluarkan, mengirim (surat)" },
  { kanji: "~度(度)", kana: "~ど(にじゅうはちど)", answers: ["~derajat ( derajat)", "~jam", "~menit", "~meter"], correct: "~derajat ( derajat)" },
  { kanji: "~点(点)", kana: "~てん(100てん)", answers: ["Nilai (nilai 100)", "Harga", "Jumlah", "Nomor"], correct: "Nilai (nilai 100)" },
  { kanji: "服", kana: "ふく", answers: ["Baju, pakaian", "Sepatu", "Topi", "Tas"], correct: "Baju, pakaian" },
  { kanji: "自転車", kana: "じてんしゃ", answers: ["Sepeda", "Motor", "Mobil", "Kereta"], correct: "Sepeda" },
  { kanji: "自動車", kana: "じどうしゃ", answers: ["Mobil", "Sepeda", "Becak", "Truk"], correct: "Mobil" },
  { kanji: "売ります", kana: "うります", answers: ["Menjual", "Membeli", "Membuat", "Memakai"], correct: "Menjual" },
  { kanji: "貸します", kana: "かします", answers: ["Meminjamkan", "Meminjam", "Membeli", "Menjual"], correct: "Meminjamkan" },
  { kanji: "返します", kana: "かえします", answers: ["Mengembalikan", "Membawa", "Membeli", "Membuang"], correct: "Mengembalikan" },
  { kanji: "変わります", kana: "かわります", answers: ["Mengganti", "Berhenti", "Mulai", "Pergi"], correct: "Mengganti" },
  { kanji: "~用", kana: "~よう", answers: ["Urusan, keperluan", "Hobi", "Tugas", "Arah"], correct: "Urusan, keperluan" },
  { kanji: "子供用", kana: "こどもよう", answers: ["Urusan anak", "Urusan bayi", "Urusan sekolah", "Urusan main"], correct: "Urusan anak" },
  { kanji: "人生", kana: "じんせい", answers: ["Kehidupan", "Kematian", "Dunia", "Masa lalu"], correct: "Kehidupan" },
  { kanji: "歌手", kana: "かしゅ", answers: ["Penyanyi", "Pelukis", "Penulis", "Atlit"], correct: "Penyanyi" },
  { kanji: "選手", kana: "せんしゅ", answers: ["Atlit, pemain", "Pelatih", "Penonton", "Wasit"], correct: "Atlit, pemain" },
  { kanji: "画家", kana: "がか", answers: ["Pelukis", "Penulis", "Penyanyi", "Penari"], correct: "Pelukis" },
  { kanji: "作家", kana: "さっか", answers: ["Pengarang", "Pembaca", "Penjual", "Pembeli"], correct: "Pengarang" },
  { kanji: "入学", kana: "にゅうがく", answers: ["Masuk sekolah", "Lulus sekolah", "Libur sekolah", "Ujian sekolah"], correct: "Masuk sekolah" },
  { kanji: "卒業", kana: "そつぎょう", answers: ["Lulus", "Masuk", "Mulai", "Gagal"], correct: "Lulus" },
  { kanji: "病気", kana: "びょうき", answers: ["Sakit", "Sehat", "Lelah", "Lapar"], correct: "Sakit" },
  { kanji: "若い", kana: "わかい", answers: ["Muda", "Tua", "Besar", "Kecil"], correct: "Muda" },
  { kanji: "生まれます", kana: "うまれます", answers: ["Lahir", "Mati", "Tumbuh", "Sakit"], correct: "Lahir" },
  { kanji: "思い出", kana: "おもいで", answers: ["Kenang-kenangan, kenangan", "Masa depan", "Cita-cita", "Tugas"], correct: "Kenang-kenangan, kenangan" },
  { kanji: "生活", kana: "せいかつ", answers: ["Kehidupan", "Pekerjaan", "Pelajaran", "Hobi"], correct: "Kehidupan" },
  { kanji: "映画", kana: "えいが", answers: ["Film", "Musik", "Buku", "Gambar"], correct: "Film" },
  { kanji: "夫", kana: "おっと", answers: ["Suami (sendiri)", "Istri", "Ayah", "Paman"], correct: "Suami (sendiri)" },
  { kanji: "妻", kana: "つま", answers: ["Istri (sendiri)", "Suami", "Ibu", "Bibi"], correct: "Istri (sendiri)" },
  { kanji: "両親", kana: "りょうしん", answers: ["Orang tua", "Anak", "Saudara", "Teman"], correct: "Orang tua" },
  { kanji: "不便", kana: "ふべん", answers: ["Tidak praktis", "Praktis", "Mudah", "Sulit"], correct: "Tidak praktis" },
  { kanji: "選びます", kana: "えらびます", answers: ["Memilih", "Membuang", "Membeli", "Menjual"], correct: "Memilih" },
  { kanji: "寝ます", kana: "ねます", answers: ["Tidur", "Bangun", "Makan", "Mandi"], correct: "Tidur" },
  { kanji: "サッカー場", kana: "サッカーじょう", answers: ["Lapangan sepak bola", "Gedung olahraga", "Taman bermain", "Stadion"], correct: "Lapangan sepak bola" },
  { kanji: "試合", kana: "しあい", answers: ["Pertandingan", "Latihan", "Pelajaran", "Hobi"], correct: "Pertandingan" },
  { kanji: "強い", kana: "つよい", answers: ["Kuat", "Lemah", "Besar", "Kecil"], correct: "Kuat" },
  { kanji: "弱い", kana: "よわい", answers: ["Lemah", "Kuat", "Berani", "Takut"], correct: "Lemah" },
  { kanji: "勝ちます", kana: "かちます", answers: ["Menang", "Kalah", "Seri", "Batal"], correct: "Menang" },
  { kanji: "負けます", kana: "まけます", answers: ["Kalah", "Menang", "Menyerah", "Berhenti"], correct: "Kalah" },
  { kanji: "~対~(対)", kana: "~たい~(inたいいち)", answers: ["~lawan~ ( lawan )", "~sama~", "~dan~", "~atau~"], correct: "~lawan~ ( lawan )" },
  { kanji: "庭", kana: "にわ", answers: ["Halaman", "Rumah", "Jalan", "Kebun"], correct: "Halaman" },
  { kanji: "公園", kana: "こうえん", answers: ["Taman", "Hutan", "Gunung", "Pasar"], correct: "Taman" },
  { kanji: "病院", kana: "びょういん", answers: ["Rumah sakit", "Sekolah", "Kantor", "Stasiun"], correct: "Rumah sakit" },
  { kanji: "交通", kana: "こうつう", answers: ["Lalu lintas", "Perjalanan", "Angkutan", "Jalan"], correct: "Lalu lintas" },
  { kanji: "通勤", kana: "つうきん", answers: ["Perjalanan ke kantor", "Perjalanan sekolah", "Wisata", "Mudik"], correct: "Perjalanan ke kantor" },
  { kanji: "安全", kana: "あんぜん", answers: ["Keselamatan", "Bahaya", "Resiko", "Tugas"], correct: "Keselamatan" },
  { kanji: "危ない", kana: "あぶない", answers: ["Bahaya", "Aman", "Mudah", "Indah"], correct: "Bahaya" },
  { kanji: "遠い", kana: "とおい", answers: ["Jauh", "Dekat", "Samping", "Luar"], correct: "Jauh" },
  { kanji: "努めます", kana: "つとめます", answers: ["Bekerja", "Belajar", "Bermain", "Berhenti"], correct: "Bekerja" },
  { kanji: "~以上(時間以上)", kana: "~いじょう(inじかんいじょう)", answers: ["~ lebih ( jam lebih)", "~ kurang", "~ sama", "~ lama"], correct: "~ lebih ( jam lebih)" },
  { kanji: "~以下(万円以下)", kana: "~いか(ろくまんえんいか)", answers: ["~kurang (kurang dari  man yen)", "~lebih", "~mahal", "~murah"], correct: "~kurang (kurang dari  man yen)" },
  { kanji: "海外", kana: "かいがい", answers: ["Luar negri", "Dalam negri", "Pulau lain", "Kota lain"], correct: "Luar negri" },
  { kanji: "食生活", kana: "しょくせいかつ", answers: ["Susunan makanan", "Cara masak", "Tempat makan", "Waktu makan"], correct: "Susunan makanan" },
  { kanji: "健康", kana: "けんこう", answers: ["Kesehatan", "Sakit", "Obat", "Dokter"], correct: "Kesehatan" },
  { kanji: "家庭料理", kana: "かていりょうり", answers: ["Masakan rumah tangga", "Masakan restoran", "Masakan jepang", "Masakan barat"], correct: "Masakan rumah tangga" },
  { kanji: "材料", kana: "ざいりょう", answers: ["Bahan", "Alat", "Tempat", "Hasil"], correct: "Bahan" },
  { kanji: "量", kana: "りょう", answers: ["Jumlah, kuantitas, banyaknya", "Harga", "Rasa", "Warna"], correct: "Jumlah, kuantitas, banyaknya" },
  { kanji: "米", kana: "こめ", answers: ["Beras", "Nasi", "Gandum", "Jagung"], correct: "Beras" },
  { kanji: "~食", kana: "~しょく", answers: ["Makan -", "Minum -", "Beli -", "Masak -"], correct: "Makan -" },
  { kanji: "朝食", kana: "ちょうしょく", answers: ["Makan pagi", "Makan siang", "Makan malam", "Makan ringan"], correct: "Makan pagi" },
  { kanji: "昼食", kana: "ちゅうしょく", answers: ["Makan siang", "Makan pagi", "Makan malam", "Makan luar"], correct: "Makan siang" },
  { kanji: "夕食", kana: "ゆうしょく", answers: ["Makan malam", "Makan sore", "Makan siang", "Makan pagi"], correct: "Makan malam" },
  { kanji: "外食", kana: "がいしょく", answers: ["Makan di luar", "Makan di rumah", "Masak sendiri", "Beli makanan"], correct: "Makan di luar" },
  { kanji: "定食", kana: "ていしょく", answers: ["Makanan dengan menu tetap", "Makanan bebas", "Makanan ringan", "Makanan pembuka"], correct: "Makanan dengan menu tetap" },
  { kanji: "住所", kana: "じゅうしょ", answers: ["Alamat", "Nama", "Umur", "Pekerjaan"], correct: "Alamat" },
  { kanji: "訪問", kana: "ほうもん", answers: ["Kunjungan", "Pertemuan", "Janji", "Telepon"], correct: "Kunjungan" },
  { kanji: "経験", kana: "けいけん", answers: ["Pengalaman", "Pelajaran", "Tugas", "Ujian"], correct: "Pengalaman" },
  { kanji: "親切", kana: "しんせつ", answers: ["Ramah", "Jahat", "Marah", "Pelit"], correct: "Ramah" },
  { kanji: "座ります", kana: "すわります", answers: ["Duduk", "Berdiri", "Berjalan", "Lari"], correct: "Duduk" },
  { kanji: "立ちます", kana: "たちます", answers: ["Berdiri", "Duduk", "Tidur", "Lompat"], correct: "Berdiri" },
  { kanji: "~観(人生観)", kana: "~かん(じんせいかん)", answers: ["Pandangan (pandangan hidup)", "Cita-cita", "Harapan", "Masa lalu"], correct: "Pandangan (pandangan hidup)" },
  { kanji: "约~(约年間)", kana: "やく~(やくろくねんかん)", answers: ["Kira, sekitar (sekitar  tahun)", "Pasti", "Selama", "Tepat"], correct: "Kira, sekitar (sekitar  tahun)" },
  { kanji: "計画", kana: "けいかく", answers: ["Rencana, program", "Hasil", "Laporan", "Tugas"], correct: "Rencana, program" },
  { kanji: "自信", kana: "じしん", answers: ["Percaya diri", "Takut", "Ragu", "Berani"], correct: "Percaya diri" },
  { kanji: "方法", kana: "ほうほう", answers: ["Cara", "Hasil", "Tujuan", "Bahan"], correct: "Cara" },
  { kanji: "目的", kana: "もくてき", answers: ["Tujuan", "Cara", "Hasil", "Rencana"], correct: "Tujuan" },
  { kanji: "難しい", kana: "むずかしい", answers: ["Sulit", "Mudah", "Indah", "Bagus"], correct: "Sulit" },
  { kanji: "通じます", kana: "つうじます", answers: ["Mengalirkan, menguasai, berhubungan", "Memutus", "Berhenti", "Mulai"], correct: "Mengalirkan, menguasai, berhubungan" },
  { kanji: "習います", kana: "ならいます", answers: ["Belajar kepada", "Mengajar", "Melihat", "Mencari"], correct: "Belajar kepada" },
  { kanji: "学びます", kana: "まなびます", answers: ["Belajar", "Bermain", "Bekerja", "Beristirahat"], correct: "Belajar" },
  { kanji: "~級", kana: "~きゅう", answers: ["Kelas, tingkat ~", "Tahun ~", "Orang ~", "Bahasa ~"], correct: "Kelas, tingkat ~" },
  { kanji: "初級", kana: "しょきゅう", answers: ["Kelas dasar", "Kelas menengah", "Kelas atas", "Kelas ahli"], correct: "Kelas dasar" },
  { kanji: "中級", kana: "ちゅうきゅう", answers: ["Kelas menengah", "Kelas dasar", "Kelas atas", "Kelas pemula"], correct: "Kelas menengah" },
  { kanji: "上級", kana: "じょうきゅう", answers: ["Kelas atas", "Kelas dasar", "Kelas menengah", "Kelas rendah"], correct: "Kelas atas" },
  { kanji: "相手", kana: "あいて", answers: ["Pasangan, lawan", "Teman", "Saudara", "Guru"], correct: "Pasangan, lawan" },
  { kanji: "気持ち", kana: "きもち", answers: ["Perasaan", "Sakit", "Lelah", "Sedih"], correct: "Perasaan" },
  { kanji: "恋人", kana: "こいびと", answers: ["Pacar", "Teman", "Musuh", "Keluarga"], correct: "Pacar" },
  { kanji: "出会い", kana: "であい", answers: ["Pertemuan", "Perpisahan", "Perjalanan", "Liburan"], correct: "Pertemuan" },
  { kanji: "最近", kana: "さいきん", answers: ["Akhir-akhir ini", "Dulu", "Nanti", "Selamanya"], correct: "Akhir-akhir ini" },
  { kanji: "最高", kana: "さいこう", answers: ["Teratas, tertinggi", "Terendah", "Terlama", "Terbaru"], correct: "Teratas, tertinggi" },
  { kanji: "出席", kana: "しゅっせき", answers: ["Kehadiran", "Ketidakhadiran", "Izin", "Sakit"], correct: "Kehadiran" },
  { kanji: "招待", kana: "しょうたい", answers: ["Undangan", "Perintah", "Anjuran", "Tugas"], correct: "Undangan" },
  { kanji: "~合う(知り合う)", kana: "~あう(しりあう)", answers: ["Cocok (kenal mengenal)", "Beda", "Jauh", "Dekat"], correct: "Cocok (kenal mengenal)" },
  { kanji: "社会人", kana: "しゃかいじん", answers: ["Anggota masyarakat", "Pelajar", "Guru", "Pejabat"], correct: "Anggota masyarakat" },
  { kanji: "職場", kana: "しょくば", answers: ["Tempat kerja", "Sekolah", "Pasar", "Rumah"], correct: "Tempat kerja" },
  { kanji: "給料", kana: "きゅうりょう", answers: ["Gaji", "Bonus", "Hutang", "Tabungan"], correct: "Gaji" },
  { kanji: "人間関係", kana: "にんげんかんけい", answers: ["Hubungan antar manusia", "Hubungan keluarga", "Hubungan bisnis", "Hubungan internasional"], correct: "Hubungan antar manusia" },
  { kanji: "親友", kana: "しんゆう", answers: ["Teman karib", "Teman lama", "Teman baru", "Musuh"], correct: "Teman karib" },
  { kanji: "恋愛", kana: "れんあい", answers: ["Percintaan, asmara", "Pertemanan", "Kebencian", "Persaudaraan"], correct: "Percintaan, asmara" },
  { kanji: "相談", kana: "そうだん", answers: ["Musyawarah", "Perintah", "Laporan", "Cerita"], correct: "Musyawarah" },
  { kanji: "心", kana: "こころ", answers: ["Hati", "Kepala", "Badan", "Tangan"], correct: "Hati" },
  { kanji: "心配", kana: "しんぱい", answers: ["Khawatir", "Berani", "Senang", "Tenang"], correct: "Khawatir" },
  { kanji: "不安", kana: "ふあん", answers: ["Kegelisahan, kekhawatiran", "Keamanan", "Ketenangan", "Kebahagiaan"], correct: "Kegelisahan, kekhawatiran" },
  { kanji: "お客様", kana: "おきゃくさま", answers: ["Tamu", "Pemilik", "Pelayan", "Pedagang"], correct: "Tamu" },
  { kanji: "手続き", kana: "てつづき", answers: ["Prosedur", "Hasil", "Laporan", "Tugas"], correct: "Prosedur" },
  { kanji: "飛行機", kana: "ひこうき", answers: ["Pesawat terbang", "Kapal laut", "Kereta api", "Mobil"], correct: "Pesawat terbang" },
  { kanji: "变更", kana: "へんこう", answers: ["Perubahan", "Tetap", "Sama", "Lama"], correct: "Perubahan" },
  { kanji: "予定", kana: "よてい", answers: ["Rencana", "Hasil", "Tugas", "Ujian"], correct: "Rencana" },
  { kanji: "利用", kana: "りよう", answers: ["Penggunaan, pemakaian", "Pembuangan", "Pembelian", "Penjualan"], correct: "Penggunaan, pemakaian" },
  { kanji: "忘れ物", kana: "わすれもの", answers: ["Benda yang tertinggal", "Benda baru", "Benda mahal", "Benda hilang"], correct: "Benda yang tertinggal" },
  { kanji: "助けます", kana: "たすけます", answers: ["Menolong", "Memukul", "Melihat", "Mengabaikan"], correct: "Menolong" },
  { kanji: "~航空(JF航空)", kana: "~こうくう(JFこうくう)", answers: ["Penerbangan (penerbangan JF)", "Pelayaran", "Perjalanan", "Angkutan"], correct: "Penerbangan (penerbangan JF)" },
  { kanji: "~便(便)", kana: "~びん(いちいちごぴん)", answers: ["Penerbangan, pos (pos  )", "Kereta", "Mobil", "Kapal"], correct: "Penerbangan, pos (pos  )" },
  { kanji: "体力", kana: "たいりょく", answers: ["Kekuatan", "Kelemahan", "Kecepatan", "Kepintaran"], correct: "Kekuatan" },
  { kanji: "協力", kana: "きょうりょく", answers: ["Kerjasama", "Persaingan", "Perpecahan", "Permusuhan"], correct: "Kerjasama" },
  { kanji: "担当", kana: "たんとう", answers: ["Petugas", "Pemimpin", "Tamu", "Pelayan"], correct: "Petugas" },
  { kanji: "報告", kana: "ほうこく", answers: ["Melapor", "Mendengar", "Melihat", "Bertanya"], correct: "Melapor" },
  { kanji: "連絡", kana: "れんらく", answers: ["Menghubungi", "Menjauhi", "Melihat", "Menunggu"], correct: "Menghubungi" },
  { kanji: "募集", kana: "ぼしゅう", answers: ["Penerimaan, perekrutan", "Pemberhentian", "Penolakan", "Pengunduran diri"], correct: "Penerimaan, perekrutan" },
  { kanji: "輸出", kana: "ゆしゅつ", answers: ["Ekspor", "Impor", "Produksi", "Konsumsi"], correct: "Ekspor" },
  { kanji: "輸入", kana: "ゆにゅう", answers: ["Impor", "Ekspor", "Jual", "Beli"], correct: "Impor" },
  { kanji: "会話", kana: "かいわ", answers: ["Percakapan", "Tulisan", "Bacaan", "Lagu"], correct: "Percakapan" },
  { kanji: "形", kana: "かたち", answers: ["Bentuk", "Warna", "Rasa", "Harga"], correct: "Bentuk" },
  { kanji: "漢字", kana: "かんじ", answers: ["Kanji", "Hiragana", "Katakana", "Romaji"], correct: "Kanji" },
  { kanji: "答え", kana: "こたえ", answers: ["Jawaban", "Pertanyaan", "Cerita", "Tugas"], correct: "Jawaban" },
  { kanji: "質問", kana: "しつもん", answers: ["Pertanyaan", "Jawaban", "Laporan", "Perintah"], correct: "Pertanyaan" },
  { kanji: "正しい", kana: "ただしい", answers: ["Benar", "Salah", "Bagus", "Indah"], correct: "Benar" },
  { kanji: "読解", kana: "どっかい", answers: ["Bacaan", "Tulisan", "Lagu", "Musik"], correct: "Bacaan" },
  { kanji: "表現", kana: "ひょうげん", answers: ["Pengucapan", "Tulisan", "Gambar", "Rasa"], correct: "Pengucapan" },
  { kanji: "文", kana: "ぶん", answers: ["Kalimat", "Kata", "Huruf", "Buku"], correct: "Kalimat" },
  { kanji: "文型", kana: "ぶんけい", answers: ["Pola kalimat", "Bentuk kata", "Arti kalimat", "Gaya bahasa"], correct: "Pola kalimat" },
  { kanji: "文法", kana: "ぶんぽう", answers: ["Tata Bahasa", "Arti kata", "Cara baca", "Hobi"], correct: "Tata Bahasa" },
  { kanji: "もう一度", kana: "もういちど", answers: ["Sekali lagi", "Sudah cukup", "Jangan lagi", "Terakhir kali"], correct: "Sekali lagi" },
  { kanji: "例", kana: "れい", answers: ["Contoh", "Tugas", "Ujian", "Hasil"], correct: "Contoh" },
  { kanji: "練習", kana: "れんしゅう", answers: ["latihan", "pertandingan", "liburan", "pelajaran"], correct: "latihan" },
  { kanji: "~枚", kana: "~まい", answers: ["- lembar", "buah", "orang", "kali"], correct: "- lembar" },
  { kanji: "今週", kana: "こんしゅう", answers: ["Minggu ini", "Minggu lalu", "Minggu depan", "Setiap minggu"], correct: "Minggu ini" },
  { kanji: "今度", kana: "こんど", answers: ["Lain kali, yang akan datang", "Tadi", "Dulu", "Sekarang"], correct: "Lain kali, yang akan datang" },
  { kanji: "横", kana: "よこ", answers: ["Sebelah", "Depan", "Belakang", "Dalam"], correct: "Sebelah" },
  { kanji: "押します", kana: "おします", answers: ["Menekan, mendorong", "Menarik", "Membuang", "Membeli"], correct: "Menekan, mendorong" },
  { kanji: "引きます", kana: "ひきます", answers: ["Menarik", "Mendorong", "Menekan", "Membawa"], correct: "Menarik" },
  { kanji: "温泉", kana: "おんせん", answers: ["Pemandian air panas", "Kolam renang", "Sungai", "Laut"], correct: "Pemandian air panas" },
  { kanji: "来週", kana: "らいしゅう", answers: ["Minggu depan", "Minggu ini", "Minggu lalu", "Tiap minggu"], correct: "Minggu depan" },
  { kanji: "犬", kana: "いぬ", answers: ["Anjing", "Kucing", "Kelinci", "Burung"], correct: "Anjing" },
  { kanji: "夕方", kana: "ゆうがた", answers: ["Sore", "Pagi", "Siang", "Malam"], correct: "Sore" },
  { kanji: "季節", kana: "きせつ", answers: ["Musim", "Cuaca", "Waktu", "Bulan"], correct: "Musim" },
  { kanji: "昨日", kana: "きのう", answers: ["Kemarin", "Besok", "Hari ini", "Lusa"], correct: "Kemarin" },
  { kanji: "明日", kana: "あした", answers: ["Besok", "Kemarin", "Hari ini", "Lusa"], correct: "Besok" },
  { kanji: "食堂", kana: "しょくどう", answers: ["Kantin", "Kantor", "Rumah", "Pasar"], correct: "Kantin" },
  { kanji: "銀行", kana: "ぎんこう", answers: ["Bank", "Stasiun", "Kantor pos", "Toko"], correct: "Bank" },
  { kanji: "受付", kana: "うけつけ", answers: ["Resepsionis", "Manajer", "Pelayan", "Kasir"], correct: "Resepsionis" },
  { kanji: "門", kana: "もん", answers: ["Pintu gerbang", "Pintu rumah", "Jendela", "Pagar"], correct: "Pintu gerbang" },
  { kanji: "登ります", kana: "のぼります", answers: ["Mendaki", "Turun", "Berjalan", "Lari"], correct: "Mendaki" },
  { kanji: "教科書", kana: "きょうかしょ", answers: ["Buku panduan", "Buku tulis", "Buku cerita", "Majalah"], correct: "Buku panduan" },
  { kanji: "教室", kana: "きょうしつ", answers: ["Ruang kelas", "Ruang guru", "Ruang makan", "Ruang tamu"], correct: "Ruang kelas" },
  { kanji: "参加します", kana: "さんかします", answers: ["Berpartisipasi", "Menonton", "Menolak", "Pergi"], correct: "Berpartisipasi" },
  { kanji: "用意します", kana: "よういします", answers: ["Menyiapkan", "Membuang", "Membeli", "Menjual"], correct: "Menyiapkan" },
  { kanji: "牛肉", kana: "ぎゅうにく", answers: ["Daging sapi", "Daging babi", "Daging ayam", "Ikan"], correct: "Daging sapi" },
  { kanji: "豚肉", kana: "ぶたにく", answers: ["Daging babi", "Daging sapi", "Daging kambing", "Daging ayam"], correct: "Daging babi" },
  { kanji: "皿", kana: "さら", answers: ["Piring", "Gelas", "Sendok", "Garpu"], correct: "Piring" },
  { kanji: "お湯", kana: "おゆ", answers: ["Air panas", "Air dingin", "Air es", "Air mineral"], correct: "Air panas" },
  { kanji: "調理方法", kana: "ちょうりほうほう", answers: ["Cara memasak", "Cara makan", "Cara beli", "Cara potong"], correct: "Cara memasak" },
  { kanji: "甘い", kana: "あまい", answers: ["Manis", "Asin", "Pahit", "Pedas"], correct: "Manis" },
  { kanji: "辛い", kana: "からい", answers: ["Pedas", "Manis", "Asam", "Asin"], correct: "Pedas" },
  { kanji: "数字", kana: "すうじ", answers: ["Angka, bilangan", "Huruf", "Kata", "Kalimat"], correct: "Angka, bilangan" },
  { kanji: "机", kana: "つくえ", answers: ["Meja", "Kursi", "Lemari", "Papan"], correct: "Meja" },
  { kanji: "都合", kana: "つごう", answers: ["Keadaan", "Waktu", "Tempat", "Orang"], correct: "Keadaan" },
  { kanji: "用事", kana: "ようじ", answers: ["Keperluan", "Hobi", "Tugas", "Janji"], correct: "Keperluan" },
  { kanji: "氏名", kana: "しめい", answers: ["Nama lengkap", "Nama panggilan", "Alamat", "Umur"], correct: "Nama lengkap" },
  { kanji: "理由", kana: "りゆう", answers: ["Alasan", "Hasil", "Tujuan", "Cara"], correct: "Alasan" },
  { kanji: "別に", kana: "べつに", answers: ["Beda-beda", "Sama saja", "Khusus", "Umum"], correct: "Beda-beda" },
  { kanji: "連絡先", kana: "れんらくさき", answers: ["Alamat yang dapat dihubungi", "Rumah lama", "Tempat kerja", "Sekolah"], correct: "Alamat yang dapat dihubungi" },
  { kanji: "吸います", kana: "すいます", answers: ["Menghisap", "Membuang", "Makan", "Minum"], correct: "Menghisap" },
  { kanji: "取ります", kana: "とります", answers: ["Mengambil", "Memeberi", "Membuang", "Menaruh"], correct: "Mengambil" },
  { kanji: "伝えます", kana: "つたえます", answers: ["Menyampaikan", "Mendengar", "Melihat", "Melupakan"], correct: "Menyampaikan" },
  { kanji: "熱", kana: "ねつ", answers: ["Demam", "Sakit", "Obat", "Dokter"], correct: "Demam" },
  { kanji: "薬", kana: "くすり", answers: ["Obat", "Racun", "Makanan", "Minuman"], correct: "Obat" },
  { kanji: "医者", kana: "いしゃ", answers: ["Dokter", "Guru", "Polisi", "Suster"], correct: "Dokter" },
  { kanji: "~才", kana: "~さい", answers: ["Bakat / umur", "Tahun", "Kelas", "Nomor"], correct: "Bakat / umur" },
  { kanji: "眠い", kana: "ねむい", answers: ["Ngantuk", "Lelah", "Sakit", "Lapar"], correct: "Ngantuk" },
  { kanji: "記入します", kana: "きにゅうします", answers: ["Mengisi di kertas", "Membaca buku", "Menulis surat", "Membeli pena"], correct: "Mengisi di kertas" },
  { kanji: "顏", kana: "かお", answers: ["Wajah", "Tangan", "Kaki", "Badan"], correct: "Wajah" },
  { kanji: "泣きます", kana: "なきます", answers: ["Menangis", "Tertawa", "Marah", "Senang"], correct: "Menangis" },
  { kanji: "会計", kana: "かいけい", answers: ["Pembayaran", "Laporan", "Tugas", "Ujian"], correct: "Pembayaran" },
  { kanji: "電話番号", kana: "でんわばんごう", answers: ["Nomor telepon", "Nomor rumah", "Nomor sepatu", "Nomor antri"], correct: "Nomor telepon" },
  { kanji: "牛乳", kana: "ぎゅうにゅう", answers: ["Susu sapi", "Air putih", "Teh", "Kopi"], correct: "Susu sapi" },
  { kanji: "禁煙", kana: "きんえん", answers: ["Larangan merokok", "Larangan makan", "Larangan berisik", "Larangan masuk"], correct: "Larangan merokok" },
  { kanji: "自由", kana: "じゅう", answers: ["Bebas", "Terikat", "Sulit", "Mahal"], correct: "Bebas" },
  { kanji: "切ります", kana: "きります", answers: ["Memotong", "Menyambung", "Membeli", "Menjual"], correct: "Memotong" },
  { kanji: "焼きます", kana: "やきます", answers: ["Memanggang", "Merebus", "Menggoreng", "Memotong"], correct: "Memanggang" },
  { kanji: "旅館", kana: "りょかん", answers: ["Penginapan", "Rumah", "Sekolah", "Kantor"], correct: "Penginapan" },
  { kanji: "遊びます", kana: "あそびます", answers: ["Bermain", "Bekerja", "Belajar", "Tidur"], correct: "Bermain" },
  { kanji: "調べます", kana: "しらべます", answers: ["Memeriksa", "Melihat", "Membeli", "Membuang"], correct: "Memeriksa" },
  { kanji: "事故", kana: "じこ", answers: ["Kecelakaan", "Keberuntungan", "Kejadian", "Tugas"], correct: "Kecelakaan" },
  { kanji: "故障", kana: "こしょう", answers: ["Kerusakan", "Perbaikan", "Fungsi", "Alat"], correct: "Kerusakan" },
  { kanji: "指定席", kana: "していせき", answers: ["Tempat duduk yang ditetapkan", "Tempat bebas", "Tempat berdiri", "Tempat antri"], correct: "Tempat duduk yang ditetapkan" },
  { kanji: "光ります", kana: "ひかります", answers: ["Bercahaya, bersinar", "Gelap", "Redup", "Hilang"], correct: "Bercahaya, bersinar" },
  { kanji: "お知らせ", kana: "おしらせ", answers: ["Pengumuman", "Rahasia", "Cerita", "Tugas"], correct: "Pengumuman" },
  { kanji: "水道", kana: "すいどう", answers: ["Ledeng", "Listrik", "Jalan", "Jembatan"], correct: "Ledeng" },
  { kanji: "工事", kana: "こうじ", answers: ["Konstruksi", "Pekerjaan", "Pelajaran", "Hobi"], correct: "Konstruksi" },
  { kanji: "場合", kana: "ばあい", answers: ["Kesempatan", "Waktu", "Tempat", "Orang"], correct: "Kesempatan" },
  { kanji: "条件", kana: "じょうけん", answers: ["Syarat-syarat, kondisi", "Hasil", "Tujuan", "Bahan"], correct: "Syarat-syarat, kondisi" },
  { kanji: "開きます", kana: "ひらきます", answers: ["Membuka", "Menutup", "Berhenti", "Mulai"], correct: "Membuka" },
  { kanji: "生産します", kana: "せいさんします", answers: ["Memproduksi", "Mengkonsumsi", "Menjual", "Membeli"], correct: "Memproduksi" },
  { kanji: "体験", kana: "たいけん", answers: ["Percobaan", "Hasil", "Tugas", "Ujian"], correct: "Percobaan" },
  { kanji: "国際交流", kana: "こくさいこうりゅう", answers: ["Pertukaran budaya internasional", "Budaya lokal", "Sejarah jepang", "Pelajaran bahasa"], correct: "Pertukaran budaya internasional" },
  { kanji: "申し込みます", kana: "もうしこみます", answers: ["Melamar (pekerjaan)", "Keluar kerja", "Libur", "Mulai"], correct: "Melamar (pekerjaan)" },
  { kanji: "昨年", kana: "さくねん", answers: ["Tahun lalu", "Tahun depan", "Tahun ini", "Setiap tahun"], correct: "Tahun lalu" },
  { kanji: "每年", kana: "まいとし", answers: ["Setiap tahun", "Tahun lalu", "Tahun depan", "Awal tahun"], correct: "Setiap tahun" },
  { kanji: "袋", kana: "ふくろ", answers: ["Kantong plastik", "Tas", "Dompet", "Wadah"], correct: "Kantong plastik" },
  { kanji: "店長", kana: "てんちょう", answers: ["Manajer toko", "Pelayan", "Kasir", "Pembeli"], correct: "Manajer toko" },
  { kanji: "全員", kana: "ぜんいん", answers: ["Semuanya", "Sebagian", "Satu orang", "Tidak ada"], correct: "Semuanya" },
  { kanji: "習慣", kana: "しゅうかん", answers: ["Kebiasaan", "Hobi", "Tugas", "Ujian"], correct: "Kebiasaan" },
  { kanji: "普通", kana: "ふつう", answers: ["Biasa", "Luar biasa", "Mahal", "Murah"], correct: "Biasa" },
  { kanji: "暗い", kana: "くらい", answers: ["Gelap", "Terang", "Bersih", "Kotor"], correct: "Gelap" },
  { kanji: "怒ります", kana: "おこります", answers: ["Marah", "Senang", "Sedih", "Takut"], correct: "Marah" },
  { kanji: "入院します", kana: "にゅういんします", answers: ["Masuk rumah sakit", "Keluar rumah sakit", "Pergi dokter", "Minum obat"], correct: "Masuk rumah sakit" },
  { kanji: "退院します", kana: "たいいんします", answers: ["Keluar rumah sakit", "Masuk rumah sakit", "Sakit lagi", "Sehat"], correct: "Keluar rumah sakit" },
  { kanji: "急に", kana: "きゅうに", answers: ["Tiba-tiba", "Perlahan", "Sering", "Jarang"], correct: "Tiba-tiba" },
  { kanji: "営業します", kana: "えいぎょうします", answers: ["Mengusahakan", "Berhenti", "Mulai", "Pergi"], correct: "Mengusahakan" },
  { kanji: "案内します", kana: "あんないします", answers: ["Memandu", "Mencari", "Melihat", "Membeli"], correct: "Memandu" },
  { kanji: "値段", kana: "ねだん", answers: ["Harga", "Rasa", "Warna", "Jenis"], correct: "Harga" },
  { kanji: "価格", kana: "かかく", answers: ["Harga", "Rasa", "Warna", "Jenis"], correct: "Harga" },
  { kanji: "消費税", kana: "しょうひぜい", answers: ["Pajak konsumen", "Harga barang", "Gaji", "Diskon"], correct: "Pajak konsumen" },
  { kanji: "税別", kana: "ぜいべつ", answers: ["Harga belum termasuk pajak", "Harga pas", "Diskon", "Gratis"], correct: "Harga belum termasuk pajak" },
  { kanji: "図書館", kana: "としょかん", answers: ["Perpustakaan", "Sekolah", "Toko buku", "Museum"], correct: "Perpustakaan" },
  { kanji: "開きます", kana: "あきます", answers: ["Terbuka", "Tertutup", "Berhenti", "Mulai"], correct: "Terbuka" },
  { kanji: "閉まります", kana: "しまります", answers: ["Tertutup", "Terbuka", "Hilang", "Pindah"], correct: "Tertutup" },
  { kanji: "利用します", kana: "りようします", answers: ["Menggunakan", "Membuang", "Membeli", "Menjual"], correct: "Menggunakan" },
  { kanji: "窓口", kana: "まどぐち", answers: ["Pintu jendela", "Pintu gerbang", "Pintu rumah", "Tangga"], correct: "Pintu jendela" },
  { kanji: "郵便局", kana: "ゆうびんきょく", answers: ["Kantor pos", "Bank", "Stasiun", "Bandara"], correct: "Kantor pos" },
  { kanji: "近所", kana: "きんじょ", answers: ["Tetangga", "Teman", "Saudara", "Musuh"], correct: "Tetangga" },
  { kanji: "自動", kana: "じどう", answers: ["Otomatis", "Manual", "Lambat", "Cepat"], correct: "Otomatis" },
  { kanji: "危険", kana: "きけん", answers: ["Bahaya", "Aman", "Mudah", "Indah"], correct: "Bahaya" },
  { kanji: "～種類", kana: "～しゅるい", answers: ["～macam, jenis", "～buah", "～orang", "～kali"], correct: "～macam, jenis" },
  { kanji: "消します", kana: "けします", answers: ["Memadamkan", "Menyalakan", "Membuat", "Membeli"], correct: "Memadamkan" },
  { kanji: "捨てます", kana: "すてます", answers: ["Membuang", "Mengambil", "Menaruh", "Membeli"], correct: "Membuang" },
  { kanji: "分けます", kana: "わけます", answers: ["Membagi", "Menyatukan", "Membuang", "Mencari"], correct: "Membagi" },
  { kanji: "燃えます", kana: "もえます", answers: ["Terbakar", "Basah", "Dingin", "Hilang"], correct: "Terbakar" },
  { kanji: "設定します", kana: "せっていします", answers: ["Mengeset,menyeting", "Membuang", "Melihat", "Mencari"], correct: "Mengeset,menyeting" },
  { kanji: "地震", kana: "じしん", answers: ["Gempa", "Banjir", "Angin topan", "Hujan"], correct: "Gempa" },
  { kanji: "台風", kana: "たいふう", answers: ["Angin topan", "Gempa", "Hujan", "Salju"], correct: "Angin topan" },
  { kanji: "声", kana: "こえ", answers: ["Suara (benda hidup)", "Suara (benda mati)", "Cahaya", "Rasa"], correct: "Suara (benda hidup)" },
  { kanji: "大切な", kana: "たいせつな", answers: ["Penting", "Biasa", "Murah", "Jelek"], correct: "Penting" },
  { kanji: "進みます", kana: "すすみます", answers: ["Rekomendasi", "Berhenti", "Mundur", "Pergi"], correct: "Rekomendasi" },
  { kanji: "授業", kana: "じゅぎょう", answers: ["Pelajaran", "Hobi", "Wisata", "Pekerjaan"], correct: "Pelajaran" },
  { kanji: "大変な", kana: "たいへんな", answers: ["Berat (perasaan)", "Mudah", "Senang", "Tenang"], correct: "Berat (perasaan)" },
  { kanji: "困ります", kana: "こまります", answers: ["Susah", "Senang", "Mudah", "Bagus"], correct: "Susah" },
  { kanji: "違います", kana: "ちがいます", answers: ["Salah , berbeda", "Sama", "Benar", "Mirip"], correct: "Salah , berbeda" },
  { kanji: "慣れます", kana: "なれます", answers: ["terbiasa", "lupa", "cari", "tanya"], correct: "terbiasa" },
  { kanji: "増えます", kana: "ふえます", answers: ["Bertambah", "Berkurang", "Tetap", "Hilang"], correct: "Bertambah" },
  { kanji: "笑います", kana: "わらいます", answers: ["Tertawa", "Menangis", "Marah", "Sedih"], correct: "Tertawa" },
  { kanji: "苦労します", kana: "くろうします", answers: ["Bersakit-sakit ( dalam usaha)", "Bersenang-senang", "Berhenti", "Mulai"], correct: "Bersakit-sakit ( dalam usaha)" },
  { kanji: "希望", kana: "きぼう", answers: ["Harapan, keinginan", "Kenyataan", "Masa lalu", "Tugas"], correct: "Harapan, keinginan" },
  { kanji: "特に", kana: "とくに", answers: ["Terutama", "Biasa", "Umum", "Jarang"], correct: "Terutama" },
  { kanji: "建てます", kana: "たてます", answers: ["Mendirikan", "Meruntuhkan", "Membeli", "Menjual"], correct: "Mendirikan" },
  { kanji: "続けます", kana: "つづけます", answers: ["Melanjutkan", "Berhenti", "Mulai", "Pergi"], correct: "Melanjutkan" },
  { kanji: "役に立ちます", kana: "やくにたちます", answers: ["Bermanfaat", "Berbahaya", "Sulit", "Lama"], correct: "Bermanfaat" },
];